### ISSUE TITLE
CloudNET NPC not being able to read a specific Packet.

### ISSUE THREAD

**Issue by DxsSucuk** [CloudNetService/CloudNet-v3#1014]
### Stacktrace

https://just-paste.it/LVg1my0pWk

### Actions to reproduce

Join onto a service that has a CloudNET NPC.
Check the console.

### CloudNet version

[23.12 21:11:23.689] INFORMATION:
[23.12 21:11:23.690] INFORMATION: CloudNet Blizzard 4.0.0-RC5 4ec2a84d
[23.12 21:11:23.691] INFORMATION: Discord: <https://discord.cloudnetservice.eu/>
[23.12 21:11:23.691] INFORMATION:
[23.12 21:11:23.692] INFORMATION: ClusterId: a6b12bba-****-4e53-****-2160d7a8bc89
[23.12 21:11:23.692] INFORMATION: NodeId: Node-1
[23.12 21:11:23.692] INFORMATION: Head-NodeId: Node-1
[23.12 21:11:23.693] INFORMATION: CPU usage: (P/S) 2.31/31.39/100%
[23.12 21:11:23.693] INFORMATION: Node services memory allocation (U/R/M): 13312/13312/30120 MB
[23.12 21:11:23.694] INFORMATION: Threads: 55
[23.12 21:11:23.694] INFORMATION: Heap usage: 50/256MB
[23.12 21:11:23.694] INFORMATION: JVM: Amazon.com Inc. 17 (OpenJDK 64-Bit Server VM 17.0.3+6-LTS)
[23.12 21:11:23.695] INFORMATION: Update Repo: CloudNetService/launchermeta, Update Branch: beta
[23.12 21:11:23.695] INFORMATION:

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by derklaro** [comment]
Please provide proper information, the information you provided don't even contain an error?

**Comment by DxsSucuk** [comment]
I thought the report command would contain the stacktrace well then give me a second to copy the stacktrace

**Comment by DxsSucuk** [comment]
```log
[21:07:39] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to CloudNet-NPCs v4.0.0-RC5
com.comphenix.protocol.reflect.FieldAccessException: Field index 0 is out of bounds for length 0
	at com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:289) ~[ProtocolLib.jar:?]
	at com.github.juliarn.npclib.bukkit.protocol.ProtocolLibPacketAdapter.lambda$createPlayerInfoPacket$7(ProtocolLibPacketAdapter.java:292) ~[cloudnet-npcs.jar:?]
	at com.github.juliarn.npclib.common.npc.CommonNpc.forceTrackPlayer(CommonNpc.java:192) ~[cloudnet-npcs.jar:?]
	at com.github.juliarn.npclib.common.npc.CommonNpc.trackPlayer(CommonNpc.java:175) ~[cloudnet-npcs.jar:?]
	at com.github.juliarn.npclib.bukkit.BukkitActionController.handleMove(BukkitActionController.java:139) ~[cloudnet-npcs.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor45.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-350]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1593) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:29) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$PosRot.handle(ServerboundMovePlayerPacket.java:88) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-350]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-350]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-350]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-350]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-350]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.3.jar:git-Paper-350]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.3.jar:git-Paper-350]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-350]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by derklaro** [comment]
The NPC module is not yet updated for 1.19.3.

**Comment by DxsSucuk** [comment]
Is there are a ETA for an possible release?

**Comment by derklaro** [comment]
There is never an ETA
