### ISSUE TITLE
CloudNet Cloudflare Module can't load configuration.

### ISSUE THREAD

**Issue by DxsSucuk** [CloudNetService/CloudNet-v3#1016]
### Stacktrace

```
[24.12 17:32:39.406] SCHWERWIEGEND: Exception firing module task entry eu.cloudnetservice.driver.module.DefaultModuleTaskEntry@19382338
eu.cloudnetservice.driver.module.driver.ModuleConfigurationInvalidException: Unable to read module configuration from path modules/CloudNet-CloudFlare/config.json
        at eu.cloudnetservice.driver.module.driver.DriverModule.readConfig(DriverModule.java:94)
        at eu.cloudnetservice.modules.cloudflare.CloudNetCloudflareModule.loadConfiguration(CloudNetCloudflareModule.java:69)
        at eu.cloudnetservice.driver.module.DefaultModuleTaskEntry.fire(DefaultModuleTaskEntry.java:109)
        at eu.cloudnetservice.driver.module.DefaultModuleWrapper.fireModuleTaskEntry(DefaultModuleWrapper.java:365)
        at eu.cloudnetservice.driver.module.DefaultModuleWrapper.pushLifecycleChange(DefaultModuleWrapper.java:334)
        at eu.cloudnetservice.driver.module.DefaultModuleWrapper.startModule(DefaultModuleWrapper.java:184)
        at eu.cloudnetservice.node.command.sub.ModulesCommand.startModule(ModulesCommand.java:360)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:757)
        at cloud.commandframework.annotations.MethodCommandExecutionHandler.execute(MethodCommandExecutionHandler.java:79)
        at cloud.commandframework.execution.CommandExecutionHandler.executeFuture(CommandExecutionHandler.java:95)
        at cloud.commandframework.execution.AsynchronousCommandExecutionCoordinator.lambda$coordinateExecution$1(AsynchronousCommandExecutionCoordinator.java:86)
        at cloud.commandframework.execution.AsynchronousCommandExecutionCoordinator.lambda$coordinateExecution$3(AsynchronousCommandExecutionCoordinator.java:116)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: Failed to invoke constructor 'eu.cloudnetservice.modules.cloudflare.config.CloudflareConfigurationEntry(boolean, AuthenticationMethod, String, String, String, String, String, String, Collection)' with args [false, null, NODE, IP, EMAIL, GLOBALKEY, APIKEY, DOMAIN, [CloudflareGroupConfiguration[name=Proxy, sub=@, priority=1, weight=1]]]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$RecordAdapter.finalize(ReflectiveTypeAdapterFactory.java:528)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$RecordAdapter.finalize(ReflectiveTypeAdapterFactory.java:440)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:400)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoArray(ReflectiveTypeAdapterFactory.java:201)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$RecordAdapter.readField(ReflectiveTypeAdapterFactory.java:507)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$RecordAdapter.readField(ReflectiveTypeAdapterFactory.java:440)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:391)
        at com.google.gson.Gson.fromJson(Gson.java:1214)
        at com.google.gson.Gson.fromJson(Gson.java:1319)
        at com.google.gson.Gson.fromJson(Gson.java:1261)
        at eu.cloudnetservice.common.document.gson.JsonDocument.toInstanceOf(JsonDocument.java:155)
        at eu.cloudnetservice.driver.module.driver.DriverModule.readConfig(DriverModule.java:91)
        ... 15 more
Caused by: java.lang.NullPointerException: authenticationMethod is marked non-null but is null
        at eu.cloudnetservice.modules.cloudflare.config.CloudflareConfigurationEntry.<init>(CloudflareConfigurationEntry.java:27)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$RecordAdapter.finalize(ReflectiveTypeAdapterFactory.java:513)
        ... 29 more

```

### Actions to reproduce

Configurate the Cloudflare module and reload it with ``module reload cloudflare``

### CloudNet version

[23.12 21:11:23.689] INFORMATION:
[23.12 21:11:23.690] INFORMATION: CloudNet Blizzard 4.0.0-RC5 https://github.com/CloudNetService/CloudNet-v3/commit/4ec2a84dc177b8e7f603682891485396c8b7eb00
[23.12 21:11:23.691] INFORMATION: Discord: https://discord.cloudnetservice.eu/
[23.12 21:11:23.691] INFORMATION:
[23.12 21:11:23.692] INFORMATION: ClusterId: a6b12bba--4e53--2160d7a8bc89
[23.12 21:11:23.692] INFORMATION: NodeId: Node-1
[23.12 21:11:23.692] INFORMATION: Head-NodeId: Node-1
[23.12 21:11:23.693] INFORMATION: CPU usage: (P/S) 2.31/31.39/100%
[23.12 21:11:23.693] INFORMATION: Node services memory allocation (U/R/M): 13312/13312/30120 MB
[23.12 21:11:23.694] INFORMATION: Threads: 55
[23.12 21:11:23.694] INFORMATION: Heap usage: 50/256MB
[23.12 21:11:23.694] INFORMATION: JVM: Amazon.com Inc. 17 (OpenJDK 64-Bit Server VM 17.0.3+6-LTS)
[23.12 21:11:23.695] INFORMATION: Update Repo: CloudNetService/launchermeta, Update Branch: beta
[23.12 21:11:23.695] INFORMATION:

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by 0utplay** [comment]
Please remember that we need as much as possible: Please include the config you are talking about

**Comment by DxsSucuk** [comment]
```
{
  "entries": [
    {
      "enabled": true,
      "authenticationMethod": "GLOBAL",
      "entryName": "LQJ88BW",
      "hostAddress": "HOST",
      "email": "****@hotmail.com",
      "apiToken": "APITOKEN",
      "zoneId": "ZONEID",
      "domainName": "DOMAIN",
      "groups": [
        {
          "name": "Proxy",
          "sub": "@",
          "priority": 1,
          "weight": 1
        }
      ]
    }
  ]
}
```
Here is the config @0utplay, I replaced the information if thats okay?

**Comment by 0utplay** [comment]
Your config is just invalid. The auth method is GLOBAL_KEY

**Comment by DxsSucuk** [comment]
Would the apitoken then be my Global key?

**Comment by 0utplay** [comment]
Yes

**Comment by DxsSucuk** [comment]
Thanks!
