### ISSUE TITLE
LuckPerms Login Fehler

### ISSUE THREAD

**Issue by LevinGamer8** [CloudNetService/CloudNet-v3#1069]
### Stacktrace

[LuckPerms]: A permission check was made for player derFlaavius - 859f2a1b-0502-47cc-9ed6-fb8faf4e691e, but LuckPerms does not have any permissions data loaded for them. Perhaps their UUID has been altered since login?
java.lang.Exception: null
	at me.lucko.luckperms.bungee.listeners.BungeePermissionCheckListener.onPlayerPermissionCheck(BungeePermissionCheckListener.java:67) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor36.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at net.md_5.bungee.event.EventBus.post(EventBus.java:50) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:510) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at eu.cloudnetservice.modules.bridge.platform.bungeecord.PendingConnectionProxiedPlayer.hasPermission(PendingConnectionProxiedPlayer.java:238) ~[?:?]
	at eu.cloudnetservice.modules.syncproxy.platform.bungee.BungeeCordSyncProxyManagement.checkPlayerPermission(BungeeCordSyncProxyManagement.java:118) ~[?:?]
	at eu.cloudnetservice.modules.syncproxy.platform.bungee.BungeeCordSyncProxyManagement.checkPlayerPermission(BungeeCordSyncProxyManagement.java:42) ~[?:?]
	at eu.cloudnetservice.modules.syncproxy.platform.PlatformSyncProxyManagement.checkPlayerMaintenance(PlatformSyncProxyManagement.java:270) ~[?:?]
	at eu.cloudnetservice.modules.syncproxy.platform.bungee.BungeeCordSyncProxyListener.handleProxyLogin(BungeeCordSyncProxyListener.java:135) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at net.md_5.bungee.event.EventBus.post(EventBus.java:50) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:510) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at net.md_5.bungee.connection.InitialHandler.finish(InitialHandler.java:834) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at net.md_5.bungee.connection.InitialHandler.access$900(InitialHandler.java:83) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at net.md_5.bungee.connection.InitialHandler$5.done(InitialHandler.java:708) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at net.md_5.bungee.connection.InitialHandler$5.done(InitialHandler.java:693) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at net.md_5.bungee.http.HttpHandler.done(HttpHandler.java:82) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at net.md_5.bungee.http.HttpHandler.channelRead0(HttpHandler.java:73) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at net.md_5.bungee.http.HttpHandler.channelRead0(HttpHandler.java:18) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1373) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1236) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1285) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:cc0ab62:unknown]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Actions to reproduce

Ich habe LuckPerms auf dem Bungeecord und auf allen Unterservern installiert und bekomme jedes mal beim joinen diesen Fehler wenn ich im Wartungsmodus bin

### CloudNet version

CloudNet Blizzard 4.0.0-RC5 4ec2a84d
Discord: <https://discord.cloudnetservice.eu/>

 ClusterId: 3a3219de-****-4e8c-****-a4f6ad1d98c7
 NodeId: Node-1
 Head-NodeId: Node-1
 CPU usage: (P/S) 0.74/13.6/100%
 Node services memory allocation (U/R/M): 24500/24500/42000 MB
 Threads: 89
 Heap usage: 50/256MB
 JVM: Oracle Corporation 17 (Java HotSpot(TM) 64-Bit Server VM 17.0.4.1+1-LTS-2)
 Update Repo: CloudNetService/launchermeta, Update Branch: beta

### Issue uniqueness

- [x] Yes, this issue is unique. There are no similar issues.

**Comment by Snowiiii** [comment]
https://github.com/LuckPerms/LuckPerms/issues/2241 (Issues sollten Generel in English geschrieben sein)

**Comment by LevinGamer8** [comment]
Tut mir leid wusste ich nicht waren aber zu diesem Zeitpunkt auch mehrere

**Comment by derklaro** [comment]
Please re-attach the stack trace you're seeing as the paste link is invalid (do not use a paste, just copy in the raw stacktrace in backticks (codeblock))
