### ISSUE TITLE
Unable to invoke startApplication, changed paper.jar

### ISSUE THREAD

**Issue by devwckd** [CloudNetService/CloudNet-v3#1093]
### Stacktrace

```
[22.01 23:25:12.199] WARNING: [Island-1/SERR]: Exception in thread "main" dev.derklaro.aerogel.AerogelException: Unable to invoke method private void eu.cloudnetservice.wrapper.Wrapper.startApplication(eu.cloudnetservice.driver.event.EventManager,java.util.List) throws java.lang.Exception
[22.01 23:25:12.200] WARNING: [Island-1/SERR]: Caused by: java.lang.NoClassDefFoundError: joptsimple/OptionException
[22.01 23:25:12.201] WARNING: [Island-1/SERR]:  at java.base/java.lang.Class.forName0(Native Method)
[22.01 23:25:12.201] WARNING: [Island-1/SERR]:  at java.base/java.lang.Class.forName(Class.java:467)
[22.01 23:25:12.202] WARNING: [Island-1/SERR]:  at eu.cloudnetservice.wrapper.Wrapper.startApplication(Wrapper.java:234)
[22.01 23:25:12.202] WARNING: [Island-1/SERR]:  at dev.derklaro.aerogel.internal.util.MethodHandleUtil.invokeMethod(MethodHandleUtil.java:71)
[22.01 23:25:12.203] WARNING: [Island-1/SERR]:  at dev.derklaro.aerogel.internal.member.DefaultMemberInjector$InjectableMethod.invoke(DefaultMemberInjector.java:584)
[22.01 23:25:12.204] WARNING: [Island-1/SERR]:  at dev.derklaro.aerogel.internal.member.DefaultMemberInjector.injectMethod(DefaultMemberInjector.java:371)
[22.01 23:25:12.204] WARNING: [Island-1/SERR]:  at dev.derklaro.aerogel.internal.member.DefaultMemberInjector.injectInstanceMethods(DefaultMemberInjector.java:330)
[22.01 23:25:12.205] WARNING: [Island-1/SERR]:  at dev.derklaro.aerogel.internal.member.DefaultMemberInjector.inject(DefaultMemberInjector.java:166)
[22.01 23:25:12.205] WARNING: [Island-1/SERR]:  at dev.derklaro.aerogel.internal.context.MemberInjectionRequest.executeMemberInjection(MemberInjectionRequest.java:73)
[22.01 23:25:12.206] WARNING: [Island-1/SERR]:  at dev.derklaro.aerogel.internal.context.DefaultInjectionContext.finishConstruction(DefaultInjectionContext.java:530)
[22.01 23:25:12.206] WARNING: [Island-1/SERR]:  at dev.derklaro.aerogel.internal.context.util.ContextInstanceResolveHelper.resolveInstanceAndRemoveContext(ContextInstanceResolveHelper.java:99)
[22.01 23:25:12.207] WARNING: [Island-1/SERR]:  at dev.derklaro.aerogel.internal.context.util.ContextInstanceResolveHelper.resolveInstance(ContextInstanceResolveHelper.java:78)
[22.01 23:25:12.207] WARNING: [Island-1/SERR]:  at dev.derklaro.aerogel.internal.context.util.ContextInstanceResolveHelper.resolveInstance(ContextInstanceResolveHelper.java:62)
[22.01 23:25:12.208] WARNING: [Island-1/SERR]:  at dev.derklaro.aerogel.internal.DefaultInjector.instance(DefaultInjector.java:137)
[22.01 23:25:12.208] WARNING: [Island-1/SERR]:  at dev.derklaro.aerogel.internal.DefaultInjector.instance(DefaultInjector.java:119)
[22.01 23:25:12.209] WARNING: [Island-1/SERR]:  at eu.cloudnetservice.driver.inject.DefaultInjectionLayer.instance(DefaultInjectionLayer.java:58)
[22.01 23:25:12.209] WARNING: [Island-1/SERR]:  at eu.cloudnetservice.driver.inject.UncloseableInjectionLayer.instance(UncloseableInjectionLayer.java:58)
[22.01 23:25:12.209] WARNING: [Island-1/SERR]:  at eu.cloudnetservice.wrapper.Main.main(Main.java:72)
[22.01 23:25:12.210] WARNING: [Island-1/SERR]: Caused by: java.lang.ClassNotFoundException: joptsimple.OptionException
[22.01 23:25:12.210] WARNING: [Island-1/SERR]:  at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
[22.01 23:25:12.211] WARNING: [Island-1/SERR]:  at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
[22.01 23:25:12.211] WARNING: [Island-1/SERR]:  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[22.01 23:25:12.212] WARNING: [Island-1/SERR]:  ... 18 more
```

### Actions to reproduce

Changed the paper.jar file on the Island template and started the program,
used the slime world manager paper that can be found here https://github.com/infernalSuite/AdvancedSlimePaper/

### CloudNet version

[23.01 00:20:50.805] INFO:
[23.01 00:20:50.806] INFO: CloudNet Blizzard 4.0.0-RC6 135393f9
[23.01 00:20:50.806] INFO: Discord: <https://discord.cloudnetservice.eu/>
[23.01 00:20:50.807] INFO:
[23.01 00:20:50.807] INFO: ClusterId: d1b5c145-****-4730-****-ae9576e50fc4
[23.01 00:20:50.807] INFO: NodeId: Node-1
[23.01 00:20:50.807] INFO: Head-NodeId: Node-1
[23.01 00:20:50.807] INFO: CPU usage: (P/S) 0.29/1.94/100%
[23.01 00:20:50.808] INFO: Node services memory allocation (U/R/M): 1280/1280/4096 MB
[23.01 00:20:50.808] INFO: Threads: 45
[23.01 00:20:50.808] INFO: Heap usage: 44/256MB
[23.01 00:20:50.808] INFO: JVM: Eclipse Adoptium 17 (OpenJDK 64-Bit Server VM 17.0.4.1+1)
[23.01 00:20:50.809] INFO: Update Repo: CloudNetService/launchermeta, Update Branch: beta
[23.01 00:20:50.809] INFO:

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by derklaro** [comment]
I just tried starting the server with slime world manager (as described [here](https://github.com/InfernalSuite/AdvancedSlimePaper/blob/main/.docs/usage/install.md) using the [latest teamcity build](https://ci.infernalsuite.com/viewLog.html?buildId=348&buildTypeId=AdvancedSlimePaper_Build)) and everything works as expected for me:
```
test@4.0.0-RC7-SNAPSHOT-a658136b => ser Lobby-2 cmd ver
[23.01 08:34:36.002] INFO: [Lobby-2] [08:34:35 INFO]: Checking version, please wait...
[23.01 08:34:36.003] INFO: [Lobby-2] [08:34:35 INFO]: This server is running SlimeWorldManager version git-SlimeWorldManager-38 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: a65719c)

test@4.0.0-RC7-SNAPSHOT-a658136b => ser Lobby-2 cmd pl
[23.01 08:36:21.236] INFO: [Lobby-2] [08:36:20 INFO]: Plugins (9): CloudNet-Bridge, CloudNet-Chat, CloudNet-CloudPerms, CloudNet-NPCs, CloudNet-Signs, CloudNet-SimpleNameTags, ProtocolLib, SlimeWorldManager, spark
```

**Comment by devwckd** [comment]
I reinstalled and it worked fine, not sure about what caused the other issue lol, thanks :D
