### ISSUE TITLE
Caused by: eu.cloudnetservice.driver.network.rpc.exception.MissingAllArgsConstructorException: Missing all args constructor for class

### ISSUE THREAD

**Issue by Sithey** [CloudNetService/CloudNet-v3#1112]
### Stacktrace
```
[04.02 00:00:59.649] INFO: [Lobby-2] Caused by: eu.cloudnetservice.driver.network.rpc.exception.MissingAllArgsConstructorException: Missing all args constructor for class net.kyori.adventure.text.TextComponentImpl with args [class java.lang.String, interface java.util.List, interface net.kyori.adventure.text.format.Style]
```

### Actions to reproduce
`cloudPlayer.playerExecutor().sendChatMessage(Component.text("La party est maintenant ouverte"));`

### CloudNet version
v4-RC7

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by wasn325** [comment]
Can you provide us the complete Stacktrace?

**Comment by Sithey** [comment]
of course
[16:19:00] [Server thread/INFO]: GoMega issued server command: /f add Sithey
```
[16:19:01] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'f' in plugin FicelloCubeAPI v0.0.1-alpha
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot.jar:git-PaperSpigot-445]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[spigot.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[spigot.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [spigot.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [spigot.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-PaperSpigot-445]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [spigot.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [spigot.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [spigot.jar:git-PaperSpigot-445]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: eu.cloudnetservice.driver.network.rpc.exception.MissingAllArgsConstructorException: Missing all args constructor for class net.kyori.adventure.text.TextComponentImpl with args [class java.lang.String, interface java.util.List, interface net.kyori.adventure.text.format.Style]
	at eu.cloudnetservice.driver.network.rpc.defaults.object.data.DataClassInformation.createClassInformation(DataClassInformation.java:77) ~[wrapper.jar:4.0.0-RC7-ffd31747]
	at eu.cloudnetservice.driver.network.rpc.defaults.object.data.DataClassSerializer.lambda$new$0(DataClassSerializer.java:38) ~[wrapper.jar:4.0.0-RC7-ffd31747]
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.lambda$newMappingFunction$3(LocalLoadingCache.java:183) ~[caffeine-3.1.2.jar:?]
	at com.github.benmanes.caffeine.cache.UnboundedLocalCache.lambda$computeIfAbsent$2(UnboundedLocalCache.java:289) ~[caffeine-3.1.2.jar:?]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1740) ~[?:?]
	at com.github.benmanes.caffeine.cache.UnboundedLocalCache.computeIfAbsent(UnboundedLocalCache.java:285) ~[caffeine-3.1.2.jar:?]
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:106) ~[caffeine-3.1.2.jar:?]
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:58) ~[caffeine-3.1.2.jar:?]
	at eu.cloudnetservice.driver.network.rpc.defaults.object.data.DataClassSerializer.write(DataClassSerializer.java:79) ~[wrapper.jar:4.0.0-RC7-ffd31747]
	at eu.cloudnetservice.driver.network.rpc.defaults.object.DefaultObjectMapper.lambda$writeObject$1(DefaultObjectMapper.java:258) ~[wrapper.jar:4.0.0-RC7-ffd31747]
	at eu.cloudnetservice.driver.network.netty.buffer.NettyMutableDataBuf.writeNullable(NettyMutableDataBuf.java:185) ~[wrapper.jar:4.0.0-RC7-ffd31747]
	at eu.cloudnetservice.driver.network.rpc.defaults.object.DefaultObjectMapper.writeObject(DefaultObjectMapper.java:242) ~[wrapper.jar:4.0.0-RC7-ffd31747]
	at eu.cloudnetservice.driver.network.rpc.defaults.rpc.DefaultRPCChain.writeRPCInformation(DefaultRPCChain.java:208) ~[wrapper.jar:4.0.0-RC7-ffd31747]
	at eu.cloudnetservice.driver.network.rpc.defaults.rpc.DefaultRPCChain.fire(DefaultRPCChain.java:176) ~[wrapper.jar:4.0.0-RC7-ffd31747]
	at eu.cloudnetservice.driver.network.rpc.defaults.rpc.DefaultRPCChain.fireSync(DefaultRPCChain.java:147) ~[wrapper.jar:4.0.0-RC7-ffd31747]
	at eu.cloudnetservice.driver.network.rpc.defaults.rpc.DefaultRPCChain.fireSync(DefaultRPCChain.java:121) ~[wrapper.jar:4.0.0-RC7-ffd31747]
	at eu.cloudnetservice.modules.bridge.player.executor.PlayerExecutor.sendChatMessage(PlayerExecutor.java:123) ~[?:?]
	at fr.ficellocube.ficellocubeapi.spigot.commands.FriendsCommand.lambda$onCommand$1(FriendsCommand.java:182) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at fr.ficellocube.ficellocubeapi.spigot.commands.FriendsCommand.onCommand(FriendsCommand.java:36) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot.jar:git-PaperSpigot-445]
```

**Comment by 0utplay** [comment]
I guess we should add the TextComponent to the binding registered here: https://github.com/CloudNetService/CloudNet-v3/blob/554d56d5a3a34df3abd827d4ab8a9d8e14afc8e9/modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/PlatformBridgeManagement.java#L122

**Comment by derklaro** [comment]
Are you by any change compiling adventure into your own library? The only reason why this isn't working that I can imagine is a classloader mismatch causing the class to be loaded from a different location than the serializer is registered to... 🤔
