### ISSUE TITLE
Exception when starting service that has S3 template

### ISSUE THREAD

**Issue by phm07** [CloudNetService/CloudNet-v3#1125]
### Stacktrace

```
[17.02 20:53:41.958] SEVERE: Exception listing content of bucket cloudnet with prefix Lobby/default
java.nio.file.FileSystemException: temp/services/Lobby-1_64147fe8-28ce-4b18-aef4-955bb3c041ed/world/advancements/48cafbf7-8888-4457-83ff-b41024193270.json: Not a directory
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484)
        at java.base/java.nio.file.Files.newOutputStream(Files.java:228)
        at eu.cloudnetservice.modules.s3.S3TemplateStorage.lambda$pull$2(S3TemplateStorage.java:188)
        at eu.cloudnetservice.modules.s3.S3TemplateStorage.listAllObjects(S3TemplateStorage.java:454)
        at eu.cloudnetservice.modules.s3.S3TemplateStorage.pull(S3TemplateStorage.java:157)
        at eu.cloudnetservice.node.service.defaults.AbstractService.lambda$includeWaitingServiceTemplates$2(AbstractService.java:348)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
        at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:601)
        at eu.cloudnetservice.node.service.defaults.AbstractService.includeWaitingServiceTemplates(AbstractService.java:341)
        at eu.cloudnetservice.node.service.defaults.AbstractService.prepareService(AbstractService.java:711)
        at eu.cloudnetservice.node.service.defaults.AbstractService.updateLifecycle(AbstractService.java:262)
        at eu.cloudnetservice.node.service.defaults.AbstractService.updateLifecycle(AbstractService.java:236)
        at eu.cloudnetservice.driver.provider.SpecificCloudServiceProvider.start(SpecificCloudServiceProvider.java:160)
        at eu.cloudnetservice.node.TickLoop.startService(TickLoop.java:206)
        at eu.cloudnetservice.node.TickLoop.start(TickLoop.java:183)
        at eu.cloudnetservice.node.Node.finishStartup(Node.java:480)
        at dev.derklaro.aerogel.internal.util.MethodHandleUtil.invokeMethod(MethodHandleUtil.java:71)
        at dev.derklaro.aerogel.internal.member.DefaultMemberInjector$InjectableMethod.invoke(DefaultMemberInjector.java:584)
        at dev.derklaro.aerogel.internal.member.DefaultMemberInjector.injectMethod(DefaultMemberInjector.java:371)
        at dev.derklaro.aerogel.internal.member.DefaultMemberInjector.injectInstanceMethods(DefaultMemberInjector.java:330)
        at dev.derklaro.aerogel.internal.member.DefaultMemberInjector.inject(DefaultMemberInjector.java:166)
        at dev.derklaro.aerogel.internal.context.MemberInjectionRequest.executeMemberInjection(MemberInjectionRequest.java:73)
        at dev.derklaro.aerogel.internal.context.DefaultInjectionContext.finishConstruction(DefaultInjectionContext.java:527)
        at dev.derklaro.aerogel.internal.context.util.ContextInstanceResolveHelper.resolveInstanceAndRemoveContext(ContextInstanceResolveHelper.java:100)
        at dev.derklaro.aerogel.internal.context.util.ContextInstanceResolveHelper.resolveInstance(ContextInstanceResolveHelper.java:79)
        at dev.derklaro.aerogel.internal.context.util.ContextInstanceResolveHelper.resolveInstance(ContextInstanceResolveHelper.java:63)
        at dev.derklaro.aerogel.internal.DefaultInjector.instance(DefaultInjector.java:139)
        at dev.derklaro.aerogel.internal.DefaultInjector.instance(DefaultInjector.java:121)
        at eu.cloudnetservice.driver.inject.DefaultInjectionLayer.instance(DefaultInjectionLayer.java:58)
        at eu.cloudnetservice.driver.inject.UncloseableInjectionLayer.instance(UncloseableInjectionLayer.java:58)
        at eu.cloudnetservice.node.boot.Bootstrap.main(Bootstrap.java:66)
```

### Actions to reproduce

Start server with S3 template

### CloudNet version

```
[17.02 20:54:48.095] INFO:  
[17.02 20:54:48.100] INFO: CloudNet Blizzard 4.0.0-RC7 ffd31747
[17.02 20:54:48.100] INFO: Discord: <https://discord.cloudnetservice.eu/>
[17.02 20:54:48.103] INFO:  
[17.02 20:54:48.104] INFO: ClusterId: b524d946-****-45c6-****-4a8fcdf47225
[17.02 20:54:48.104] INFO: NodeId: Node-1
[17.02 20:54:48.104] INFO: Head-NodeId: Node-1
[17.02 20:54:48.105] INFO: CPU usage: (P/S) 15.38/100/100%
[17.02 20:54:48.105] INFO: Node services memory allocation (U/R/M): 13824/14848/25600 MB
[17.02 20:54:48.105] INFO: Threads: 57
[17.02 20:54:48.108] INFO: Heap usage: 62/256MB
[17.02 20:54:48.118] INFO: JVM: Debian 17 (OpenJDK 64-Bit Server VM 17.0.4+8-Debian-1deb11u1)
[17.02 20:54:48.119] INFO: Update Repo: CloudNetService/launchermeta, Update Branch: beta
[17.02 20:54:48.121] INFO:  
```

### Other

- S3 storage is MinIO

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by derklaro** [comment]
Can you please attach a picture of your `Lobby/default` root directory file structure and the structure inside the world and world/advancements directory?

**Comment by phm07** [comment]
``Lobby/default``:
![image](https://user-images.githubusercontent.com/22707808/219796731-80d177f3-6eaf-4a70-8e8d-274bffe896ce.png)

``Lobby/default/world``:
![image](https://user-images.githubusercontent.com/22707808/219796821-bd065c08-408c-4f40-8e37-6ff5fa09198e.png)
 
I unfortunately already deleted ``Lobby/default/world/advancements`` so that the server would start again. It was not there originally, it only appeared after I ran ``service Lobby-1 copy --includes world/*``

**Comment by derklaro** [comment]
I cannot give any advice if I have no information about that file/folder that you are referring to. Would it be possible to copy the service again (maybe to a different template, that would be possible via an inclusion) and check if there are any suspicous files? And: there is a difference between a file and a directory, I am not sure what screenshot you attached. In general S3 is not aware of directories and only files are stored, so attaching a screenshot from an S3 browser that correctly lists contents would be more helpful.

**Comment by phm07** [comment]
The attached screenshots are from a Windows network drive that is mapped to the S3 bucket via S3 drive. In the MinIO Object Browser it looks basically the same. Also there are empty folders, so how would they be stored if there is no file in them?

Anyway, I could recreate the issue by copying to the template once again. Here are the screenshots, this time from the MinIO Object Browser:

![image](https://user-images.githubusercontent.com/22707808/219865730-25b315ea-1631-42b2-9246-2f33ca5ea117.png)


![image](https://user-images.githubusercontent.com/22707808/219865751-1fbce537-e976-46a7-b2a6-06dd4bd80a35.png)
(Note the extraneous folder ``world``, I don't think it belongs here.)

![image](https://user-images.githubusercontent.com/22707808/219865759-39870f7a-21ea-469f-adac-e35283476557.png)

The file itself looks good:
![image](https://user-images.githubusercontent.com/22707808/219865859-721fe2e4-3c8c-4b4d-9b3b-6c4efff78d53.png)

For some reason this error results in ``world`` being an empty file in the resulting temporary service:
![image](https://user-images.githubusercontent.com/22707808/219866029-71e7df35-b806-4764-93ef-d750ca85f09d.png)

The error disappeared again after I deleted the ``advancements`` folder from within my mounted network drive. 
I have to add that sometimes region files are corrupted/not copied correctly and chunks are completely regenerated (entities and other data persist). However I don't know how to reproduce this issue yet.

**Comment by derklaro** [comment]
i just tried this myself and everything is working as expected. My deployed world directory is fine and can be pulled fine from the minio:
![image](https://user-images.githubusercontent.com/40468651/219885309-860debf8-9c58-4dae-b033-1eb4ea14fdc8.png)

**Comment by phm07** [comment]
I can very consistently recreate this error, I just have to delete the advancements folder, run ``service Lobby-1 copy --includes world/*`` and restart. After deleting the folder again and restarting the error is gone. If you want to I can give you access to my server so you can see it yourself.

**Comment by derklaro** [comment]
Executing your commands gives me a perfectly fine result 🤔

**Comment by 0utplay** [comment]
Stale, cant reproduce
