### ISSUE TITLE
Waterdog 2.0.0 Snapshot API / Cloudnet V4

### ISSUE THREAD

**Issue by Guillaume351** [CloudNetService/CloudNet-v3#1260]
### Stacktrace

```
[18.06 15:22:55.275] WARNING: [Proxy-1/SERR]: Caused by: java.lang.ClassNotFoundException: dev.waterdog.waterdogpe.utils.types.IReconnectHandler
[18.06 15:22:55.275] WARNING: [Proxy-1/SERR]: 	at dev.waterdog.waterdogpe.plugin.PluginClassLoader.findClass(PluginClassLoader.java:46)
[18.06 15:22:55.275] WARNING: [Proxy-1/SERR]: 	at dev.waterdog.waterdogpe.plugin.PluginClassLoader.findClass(PluginClassLoader.java:41)
[18.06 15:22:55.275] WARNING: [Proxy-1/SERR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
[18.06 15:22:55.275] WARNING: [Proxy-1/SERR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[18.06 15:22:55.275] WARNING: [Proxy-1/SERR]: 	... 26 more
```
### Actions to reproduce

Use the latest waterdog with 1.20.0 support with Cloudnet Bridge RC8

### CloudNet version

CloudNet Blizzard 4.0.0-RC8 61a0ada8

### Other

Waterdog 2.0 API changes that have been merged to the main branch break the bridge waterdog plugin. Some small changes are needed due to some classes / functions moving

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by 0utplay** [comment]
Waterdog v2 is currently not supported on `beta` nor `nightly`.

We are still waiting for waterdog to publish a release. For now only the `waterdog2` branch supports waterdog 2

**Comment by derklaro** [comment]
See #1210

**Comment by EvilJavaSkill** [comment]
I would also like the newest release version to be avaiable with CloudNetV4. I have found that the newest version is https://github.com/WaterdogPE/WaterdogPE/releases/tag/v2.0.1. Would be really nice if you can implement that.
