### ISSUE TITLE
Cannot boot services.

### ISSUE THREAD

**Issue by rmilansky** [CloudNetService/CloudNet-v3#1276]
### Stacktrace

```
[12.07 21:16:57.011] WARNING: [Lobby-1/SERR]: Exception in thread "main" dev.derklaro.aerogel.AerogelException: Unable to invoke method private void eu.cloudnetservice.wrapper.Wrapper.startApplication(eu.cloudnetservice.driver.event.EventManager,java.util.List) throws java.lang.Exception
[12.07 21:16:57.012] WARNING: [Lobby-1/SERR]: Caused by: java.lang.IllegalArgumentException
[12.07 21:16:57.012] WARNING: [Lobby-1/SERR]:   at java.instrument/sun.instrument.InstrumentationImpl.appendToClassLoaderSearch0(Native Method)
[12.07 21:16:57.013] WARNING: [Lobby-1/SERR]:   at java.instrument/sun.instrument.InstrumentationImpl.appendToSystemClassLoaderSearch(InstrumentationImpl.java:225)
[12.07 21:16:57.013] WARNING: [Lobby-1/SERR]:   at eu.cloudnetservice.wrapper.Wrapper.startApplication(Wrapper.java:228)[12.07 21:16:57.013] WARNING: [Lobby-1/SERR]:   at dev.derklaro.aerogel.internal.util.MethodHandleUtil.invokeMethod(MethodHandleUtil.java:71)
[12.07 21:16:57.013] WARNING: [Lobby-1/SERR]:   at dev.derklaro.aerogel.internal.member.DefaultMemberInjector$InjectableMethod.invoke(DefaultMemberInjector.java:584)
[12.07 21:16:57.014] WARNING: [Lobby-1/SERR]:   at dev.derklaro.aerogel.internal.member.DefaultMemberInjector.injectMethod(DefaultMemberInjector.java:371)
[12.07 21:16:57.014] WARNING: [Lobby-1/SERR]:   at dev.derklaro.aerogel.internal.member.DefaultMemberInjector.injectInstanceMethods(DefaultMemberInjector.java:330)
[12.07 21:16:57.014] WARNING: [Lobby-1/SERR]:   at dev.derklaro.aerogel.internal.member.DefaultMemberInjector.inject(DefaultMemberInjector.java:166)
[12.07 21:16:57.014] WARNING: [Lobby-1/SERR]:   at dev.derklaro.aerogel.internal.context.MemberInjectionRequest.executeMemberInjection(MemberInjectionRequest.java:73)
[12.07 21:16:57.014] WARNING: [Lobby-1/SERR]:   at dev.derklaro.aerogel.internal.context.DefaultInjectionContext.finishConstruction(DefaultInjectionContext.java:527)
[12.07 21:16:57.014] WARNING: [Lobby-1/SERR]:   at dev.derklaro.aerogel.internal.context.util.ContextInstanceResolveHelper.resolveInstanceAndRemoveContext(ContextInstanceResolveHelper.java:100)
[12.07 21:16:57.014] WARNING: [Lobby-1/SERR]:   at dev.derklaro.aerogel.internal.context.util.ContextInstanceResolveHelper.resolveInstance(ContextInstanceResolveHelper.java:79)
[12.07 21:16:57.015] WARNING: [Lobby-1/SERR]:   at dev.derklaro.aerogel.internal.context.util.ContextInstanceResolveHelper.resolveInstance(ContextInstanceResolveHelper.java:63)
[12.07 21:16:57.016] WARNING: [Lobby-1/SERR]:   at dev.derklaro.aerogel.internal.DefaultInjector.instance(DefaultInjector.java:139)
[12.07 21:16:57.016] WARNING: [Lobby-1/SERR]:   at dev.derklaro.aerogel.internal.DefaultInjector.instance(DefaultInjector.java:121)
[12.07 21:16:57.017] WARNING: [Lobby-1/SERR]:   at eu.cloudnetservice.driver.inject.DefaultInjectionLayer.instance(DefaultInjectionLayer.java:58)
[12.07 21:16:57.017] WARNING: [Lobby-1/SERR]:   at eu.cloudnetservice.driver.inject.UncloseableInjectionLayer.instance(UncloseableInjectionLayer.java:58)
[12.07 21:16:57.018] WARNING: [Lobby-1/SERR]:   at eu.cloudnetservice.wrapper.Main.main(Main.java:72)
[12.07 21:16:57.018] WARNING: [Proxy-1/SERR]: Exception in thread "main" dev.derklaro.aerogel.AerogelException: Unable to invoke method private void eu.cloudnetservice.wrapper.Wrapper.startApplication(eu.cloudnetservice.driver.event.EventManager,java.util.List) throws java.lang.Exception
[12.07 21:16:57.018] WARNING: [Proxy-1/SERR]: Caused by: java.lang.IllegalArgumentException
[12.07 21:16:57.019] WARNING: [Proxy-1/SERR]:   at java.instrument/sun.instrument.InstrumentationImpl.appendToClassLoaderSearch0(Native Method)
[12.07 21:16:57.019] WARNING: [Proxy-1/SERR]:   at java.instrument/sun.instrument.InstrumentationImpl.appendToSystemClassLoaderSearch(InstrumentationImpl.java:225)
[12.07 21:16:57.019] WARNING: [Proxy-1/SERR]:   at eu.cloudnetservice.wrapper.Wrapper.startApplication(Wrapper.java:228)[12.07 21:16:57.020] WARNING: [Proxy-1/SERR]:   at dev.derklaro.aerogel.internal.util.MethodHandleUtil.invokeMethod(MethodHandleUtil.java:71)
[12.07 21:16:57.021] WARNING: [Proxy-1/SERR]:   at dev.derklaro.aerogel.internal.member.DefaultMemberInjector$InjectableMethod.invoke(DefaultMemberInjector.java:584)
[12.07 21:16:57.021] WARNING: [Proxy-1/SERR]:   at dev.derklaro.aerogel.internal.member.DefaultMemberInjector.injectMethod(DefaultMemberInjector.java:371)
[12.07 21:16:57.021] WARNING: [Proxy-1/SERR]:   at dev.derklaro.aerogel.internal.member.DefaultMemberInjector.injectInstanceMethods(DefaultMemberInjector.java:330)
[12.07 21:16:57.021] WARNING: [Proxy-1/SERR]:   at dev.derklaro.aerogel.internal.member.DefaultMemberInjector.inject(DefaultMemberInjector.java:166)
[12.07 21:16:57.022] WARNING: [Proxy-1/SERR]:   at dev.derklaro.aerogel.internal.context.MemberInjectionRequest.executeMemberInjection(MemberInjectionRequest.java:73)
[12.07 21:16:57.022] WARNING: [Proxy-1/SERR]:   at dev.derklaro.aerogel.internal.context.DefaultInjectionContext.finishConstruction(DefaultInjectionContext.java:527)
[12.07 21:16:57.022] WARNING: [Proxy-1/SERR]:   at dev.derklaro.aerogel.internal.context.util.ContextInstanceResolveHelper.resolveInstanceAndRemoveContext(ContextInstanceResolveHelper.java:100)
[12.07 21:16:57.023] WARNING: [Proxy-1/SERR]:   at dev.derklaro.aerogel.internal.context.util.ContextInstanceResolveHelper.resolveInstance(ContextInstanceResolveHelper.java:79)
[12.07 21:16:57.023] WARNING: [Proxy-1/SERR]:   at dev.derklaro.aerogel.internal.context.util.ContextInstanceResolveHelper.resolveInstance(ContextInstanceResolveHelper.java:63)
[12.07 21:16:57.023] WARNING: [Proxy-1/SERR]:   at dev.derklaro.aerogel.internal.DefaultInjector.instance(DefaultInjector.java:139)
[12.07 21:16:57.023] WARNING: [Proxy-1/SERR]:   at dev.derklaro.aerogel.internal.DefaultInjector.instance(DefaultInjector.java:121)
[12.07 21:16:57.024] WARNING: [Proxy-1/SERR]:   at eu.cloudnetservice.driver.inject.DefaultInjectionLayer.instance(DefaultInjectionLayer.java:58)
[12.07 21:16:57.024] WARNING: [Proxy-1/SERR]:   at eu.cloudnetservice.driver.inject.UncloseableInjectionLayer.instance(UncloseableInjectionLayer.java:58)
[12.07 21:16:57.024] WARNING: [Proxy-1/SERR]:   at eu.cloudnetservice.wrapper.Main.main(Main.java:72)
```

### Actions to reproduce

Install CloudNet and run any service.

### CloudNet version

```
[12.07 21:18:22.440] INFO:
[12.07 21:18:22.440] INFO: CloudNet Blizzard 4.0.0-RC9 f6ca4c38
[12.07 21:18:22.440] INFO: Discord: <https://discord.cloudnetservice.eu/>
[12.07 21:18:22.441] INFO:
[12.07 21:18:22.441] INFO: ClusterId: 1cc50ee7-****-4517-****-d6611a62c855
[12.07 21:18:22.441] INFO: NodeId: Node-1
[12.07 21:18:22.441] INFO: Head-NodeId: Node-1
[12.07 21:18:22.442] INFO: CPU usage: (P/S) .09/.29/100%
[12.07 21:18:22.442] INFO: Node services memory allocation (U/R/M): 768/768/23988 MB
[12.07 21:18:22.442] INFO: Threads: 30
[12.07 21:18:22.442] INFO: Heap usage: 46/256MB
[12.07 21:18:22.442] INFO: JVM: Amazon.com Inc. 17 (OpenJDK 64-Bit Server VM 17.0.7+7-LTS)
[12.07 21:18:22.443] INFO: Update Repo: CloudNetService/launchermeta, Update Branch: beta
[12.07 21:18:22.443] INFO:
```

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by derklaro** [comment]
Not sure about this one. `IllegalArgumentException` is not documented to get thrown by `appendToSystemClassLoaderSearch`.
