### ISSUE TITLE
Unable to initialize database, unable to start

### ISSUE THREAD

**Issue by FatildaIV** [CloudNetService/CloudNet-v3#1277]
### Stacktrace

```
Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
Loading checksums (Update repo: CloudNetService/launchermeta, Update branch: nightly)...
Skipping download of "launcher" because the file is already up-to-date
Skipping download of "launcher-patcher" because the file is already up-to-date
Skipping download of "node" because the file is already up-to-date
Skipping download of "modules.json" because the file is already up-to-date
Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true

        ___ _                 _     __  __  _____ [Blizzard]
       / __\ | ___  _   _  __| | /\ \ \/__\/__   \
      / /  | |/ _ \| | | |/ _` |/  \/ /_\    / /\/
     / /___| | (_) | |_| | (_| / /\  //__   / /
     \____/|_|\___/ \__,_|\__,_\_\ \/\__/   \/
                               (4.0.0-RC10-SNAPSHOT-8efe65d8)

     «*» The Cloud Network Environment Technology
     «*» The modern Minecraft service management solution
     «*» Discord Support: https://discord.cloudnetservice.eu/

[15.07 11:26:13.214] INFO: Loaded 10 service versions...
[15.07 11:26:13.564] INFO: Applying needed updates to installed modules...
[15.07 11:26:13.786] INFO: Module eu.cloudnetservice.cloudnet:CloudNet-Database-MySQL:4.0.0-RC10-SNAPSHOT was successfully loaded
[15.07 11:26:13.923] INFO: Module eu.cloudnetservice.cloudnet:CloudNet-Dockerized-Services:4.0.0-RC10-SNAPSHOT was successfully loaded
[15.07 11:26:13.941] INFO: Module eu.cloudnetservice.cloudnet:CloudNet-NPCs:4.0.0-RC10-SNAPSHOT was successfully loaded
[15.07 11:26:13.948] INFO: Module eu.cloudnetservice.cloudnet:CloudNet-Rest:4.0.0-RC10-SNAPSHOT was successfully loaded
[15.07 11:26:13.985] INFO: Module eu.cloudnetservice.cloudnet:CloudNet-Report:4.0.0-RC10-SNAPSHOT was successfully loaded
[15.07 11:26:13.998] INFO: Module eu.cloudnetservice.cloudnet:CloudNet-CloudFlare:4.0.0-RC10-SNAPSHOT was successfully loaded
[15.07 11:26:14.043] INFO: Module eu.cloudnetservice.cloudnet:CloudNet-Bridge:4.0.0-RC10-SNAPSHOT was successfully loaded
[15.07 11:26:14.052] INFO: Module eu.cloudnetservice.cloudnet:CloudNet-Smart:4.0.0-RC10-SNAPSHOT was successfully loaded
[15.07 11:26:14.089] INFO: Module eu.cloudnetservice.cloudnet:CloudNet-LabyMod:4.0.0-RC10-SNAPSHOT was successfully loaded
[15.07 11:26:14.392] INFO: Module eu.cloudnetservice.cloudnet:CloudNet-SyncProxy:4.0.0-RC10-SNAPSHOT was successfully loaded
[15.07 11:26:15.666] SEVERE: Exception in thread "main"
[15.07 11:26:15.667] SEVERE: dev.derklaro.aerogel.AerogelException: Unable to invoke method private void eu.cloudnetservice.node.Node.initializeDatabaseProvider(eu.cloudnetservice.node.config.Configuration,eu.cloudnetservice.driver.registry.ServiceRegistry,eu.cloudnetservice.driver.inject.InjectionLayer,eu.cloudnetservice.driver.network.rpc.RPCFactory,eu.cloudnetservice.driver.network.rpc.RPCHandlerRegistry) throws java.lang.Exception
[15.07 11:26:15.667] SEVERE: Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Unknown system variable 'transaction_isolation'
[15.07 11:26:15.667] SEVERE:    at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596)
[15.07 11:26:15.667] SEVERE:    at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582)
[15.07 11:26:15.667] SEVERE:    at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
[15.07 11:26:15.667] SEVERE:    at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
[15.07 11:26:15.667] SEVERE:    at eu.cloudnetservice.modules.mysql.MySQLDatabaseProvider.init(MySQLDatabaseProvider.java:80)
[15.07 11:26:15.667] SEVERE:    at eu.cloudnetservice.node.Node.initializeDatabaseProvider(Node.java:251)
[15.07 11:26:15.667] SEVERE:    at dev.derklaro.aerogel.internal.util.MethodHandleUtil.invokeMethod(MethodHandleUtil.java:71)
[15.07 11:26:15.667] SEVERE:    at dev.derklaro.aerogel.internal.member.DefaultMemberInjector$InjectableMethod.invoke(DefaultMemberInjector.java:584)
[15.07 11:26:15.667] SEVERE:    at dev.derklaro.aerogel.internal.member.DefaultMemberInjector.injectMethod(DefaultMemberInjector.java:371)
[15.07 11:26:15.667] SEVERE:    at dev.derklaro.aerogel.internal.member.DefaultMemberInjector.injectInstanceMethods(DefaultMemberInjector.java:330)
[15.07 11:26:15.667] SEVERE:    at dev.derklaro.aerogel.internal.member.DefaultMemberInjector.inject(DefaultMemberInjector.java:166)
[15.07 11:26:15.667] SEVERE:    at dev.derklaro.aerogel.internal.context.MemberInjectionRequest.executeMemberInjection(MemberInjectionRequest.java:73)
[15.07 11:26:15.667] SEVERE:    at dev.derklaro.aerogel.internal.context.DefaultInjectionContext.finishConstruction(DefaultInjectionContext.java:527)
[15.07 11:26:15.667] SEVERE:    at dev.derklaro.aerogel.internal.context.util.ContextInstanceResolveHelper.resolveInstanceAndRemoveContext(ContextInstanceResolveHelper.java:100)
[15.07 11:26:15.667] SEVERE:    at dev.derklaro.aerogel.internal.context.util.ContextInstanceResolveHelper.resolveInstance(ContextInstanceResolveHelper.java:79)
[15.07 11:26:15.667] SEVERE:    at dev.derklaro.aerogel.internal.context.util.ContextInstanceResolveHelper.resolveInstance(ContextInstanceResolveHelper.java:63)
[15.07 11:26:15.667] SEVERE:    at dev.derklaro.aerogel.internal.DefaultInjector.instance(DefaultInjector.java:139)
[15.07 11:26:15.667] SEVERE:    at dev.derklaro.aerogel.internal.DefaultInjector.instance(DefaultInjector.java:121)
[15.07 11:26:15.667] SEVERE:    at eu.cloudnetservice.driver.inject.DefaultInjectionLayer.instance(DefaultInjectionLayer.java:58)
[15.07 11:26:15.667] SEVERE:    at eu.cloudnetservice.driver.inject.UncloseableInjectionLayer.instance(UncloseableInjectionLayer.java:58)
[15.07 11:26:15.667] SEVERE:    at eu.cloudnetservice.node.boot.Bootstrap.main(Bootstrap.java:66)
[15.07 11:26:15.667] SEVERE: Caused by: java.sql.SQLException: Unknown system variable 'transaction_isolation'
[15.07 11:26:15.667] SEVERE:    at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:130)
[15.07 11:26:15.667] SEVERE:    at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[15.07 11:26:15.667] SEVERE:    at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825)
[15.07 11:26:15.667] SEVERE:    at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:446)
[15.07 11:26:15.667] SEVERE:    at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239)
[15.07 11:26:15.667] SEVERE:    at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188)
[15.07 11:26:15.667] SEVERE:    at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
[15.07 11:26:15.667] SEVERE:    at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
[15.07 11:26:15.667] SEVERE:    at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
[15.07 11:26:15.667] SEVERE:    at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
[15.07 11:26:15.667] SEVERE:    at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
[15.07 11:26:15.667] SEVERE:    ... 19 more
```

### Actions to reproduce

1. Configure CloudNet with MySQL database in versions prior to RC-9.
2. Change update branch in launcher.cnl to nightly.
3. Launch CloudNet.

### CloudNet version

4.0.0-RC10-SNAPSHOT-8efe65d8

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by 0utplay** [comment]
Please provide information about the used mysql server

**Comment by FatildaIV** [comment]
> Please provide information about the used mysql server

modules/CloudNet-Database-MySQL/config.json:
```
{
  "username": "cloudnet",
  "password": "password",
  "databaseServiceName": "mysql",
  "endpoints": [
    {
      "useSsl": false,
      "database": "cloudnet",
      "address": {
        "host": "127.0.0.1",
        "port": 3306
      }
    }
  ]
}
```
Self hosted mariadb 11.0.2-2.

**Comment by 0utplay** [comment]
Using mariadb `11.1.1-RC` should resolve the issue.

**Comment by FatildaIV** [comment]
> Using mariadb `11.1.1-RC` should resolve the issue.

Fixed by replacing incompatible MySQL driver with MariaDB driver: https://mariadb.com/kb/en/about-mariadb-connector-j/
