### ISSUE TITLE
CloudNet-Bridge/WARN

### ISSUE THREAD

**Issue by Michel13xx** [CloudNetService/CloudNet-v3#1305]
### Stacktrace

`[19:57:52] [Craft Scheduler Thread - 644 - CloudNet-Bridge/WARN]: [CloudNet-Bridge] Plugin CloudNet-Bridge v1.2 generated an exception while executing task 13
java.lang.NoSuchMethodError: 'void org.bukkit.event.server.ServerListPingEvent.<init>(java.net.InetAddress, java.lang.String, int, int)'
	at de.dytanic.cloudnet.ext.bridge.bukkit.BukkitCloudNetBridgePlugin.lambda$constructServerListPingEvent$4(BukkitCloudNetBridgePlugin.java:155) ~[cloudnet-bridge.jar:?]
	at de.dytanic.cloudnet.ext.bridge.bukkit.BukkitCloudNetBridgePlugin.constructServerListPingEvent(BukkitCloudNetBridgePlugin.java:158) ~[cloudnet-bridge.jar:?]
	at de.dytanic.cloudnet.ext.bridge.bukkit.BukkitCloudNetBridgePlugin.lambda$runFireServerListPingEvent$0(BukkitCloudNetBridgePlugin.java:82) ~[cloudnet-bridge.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-169]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-169]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]`
das kommt nur noch in jeder console
habe heute denn Server erst eingerichtet
bin noch neue bei cloudnet v3

### Actions to reproduce

habe bis her nur Cloud eingerichtet und Module eingerichtet

### CloudNet version

CloudNet Earthquake 3.4.5-RELEASE-0f8f0d7 by Dytanic & the CloudNet Community

### Other

![image](https://github.com/CloudNetService/CloudNet-v3/assets/69007790/b3e8d9f9-eab0-45e9-933b-f4a247bd4b3c)

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by 0utplay** [comment]
CloudNet v3 only supports spigot versions up to 1.19.2. For any other versions consider upgrading to v4 (release candidate phase) or using solutions like ViaVersion
