### ISSUE TITLE
CloudNetV4 NoClassDefFoundError in some modules

### ISSUE THREAD

**Issue by Tiiita** [CloudNetService/CloudNet-v3#1340]
### Stacktrace

```
[11.12 01:22:31.934] INFO: [Lobby-1] [01:18:38 INFO]: [CloudNet-CloudPerms] Enabling CloudNet-CloudPerms v4.0.0-RC9
[11.12 01:22:31.934] INFO: [Lobby-1] [01:18:38 ERROR]: Error occurred while enabling CloudNet-CloudPerms v4.0.0-RC9 (Is it up to date?)
[11.12 01:22:31.934] INFO: [Lobby-1] java.lang.NoClassDefFoundError: eu/cloudnetservice/ext/platforminject/api/PlatformEntrypoint
[11.12 01:22:31.935] INFO: [Lobby-1]    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
[11.12 01:22:31.935] INFO: [Lobby-1]    at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
[11.12 01:22:31.935] INFO: [Lobby-1]    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
[11.12 01:22:31.936] INFO: [Lobby-1]    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:232) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
[11.12 01:22:31.936] INFO: [Lobby-1]    at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
[11.12 01:22:31.936] INFO: [Lobby-1]    at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:157) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
[11.12 01:22:31.936] INFO: [Lobby-1]    at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
[11.12 01:22:31.937] INFO: [Lobby-1]    at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
[11.12 01:22:31.937] INFO: [Lobby-1]    at eu.cloudnetservice.modules.cloudperms.bukkit.GeneratedBukkitCloudNet_CloudPermsEntrypoint.onEnable(GeneratedBukkitCloudNet_CloudPermsEntrypoint.java:13) ~[cloudnet-cloudperms.jar:?]
[11.12 01:22:31.937] INFO: [Lobby-1]    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
[11.12 01:22:31.937] INFO: [Lobby-1]    at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[pufferfish-1.20.1.jar:git-UniverseSpigot-"00064c2"]
[11.12 01:22:31.937] INFO: [Lobby-1]    at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[pufferfish-1.20.1.jar:git-UniverseSpigot-"00064c2"]
[11.12 01:22:31.938] INFO: [Lobby-1]    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
[11.12 01:22:31.938] INFO: [Lobby-1]    at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:655) ~[pufferfish-1.20.1.jar:git-UniverseSpigot-"00064c2"]
[11.12 01:22:31.938] INFO: [Lobby-1]    at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:566) ~[pufferfish-1.20.1.jar:git-UniverseSpigot-"00064c2"]
[11.12 01:22:31.938] INFO: [Lobby-1]    at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:632) ~[pufferfish-1.20.1.jar:git-UniverseSpigot-"00064c2"]
[11.12 01:22:31.939] INFO: [Lobby-1]    at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[pufferfish-1.20.1.jar:git-UniverseSpigot-"00064c2"]
[11.12 01:22:31.939] INFO: [Lobby-1]    at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[pufferfish-1.20.1.jar:git-UniverseSpigot-"00064c2"]
[11.12 01:22:31.939] INFO: [Lobby-1]    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1097) ~[pufferfish-1.20.1.jar:git-UniverseSpigot-"00064c2"]
[11.12 01:22:31.939] INFO: [Lobby-1]    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:314) ~[pufferfish-1.20.1.jar:git-UniverseSpigot-"00064c2"]
[11.12 01:22:31.940] INFO: [Lobby-1]    at java.lang.Thread.run(Thread.java:833) ~[?:?]
[11.12 01:22:31.940] INFO: [Lobby-1] Caused by: java.lang.ClassNotFoundException: eu.cloudnetservice.ext.platforminject.api.PlatformEntrypoint
[11.12 01:22:31.940] INFO: [Lobby-1]    at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:185) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
[11.12 01:22:31.941] INFO: [Lobby-1]    at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
[11.12 01:22:31.941] INFO: [Lobby-1]    at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
[11.12 01:22:31.941] INFO: [Lobby-1]    ... 21 more
```

### Actions to reproduce

I jost got this error when installing the new RC9 Version and selecting the cloudperms module.

### CloudNet version

```[11.12 01:30:15.296] INFO:  
[11.12 01:30:15.297] INFO: CloudNet Blizzard 4.0.0-RC9 f6ca4c38
[11.12 01:30:15.297] INFO: Discord: <https://discord.cloudnetservice.eu/>
[11.12 01:30:15.298] INFO:  
[11.12 01:30:15.298] INFO: ClusterId: 634f295c-****-4371-****-96692bb49d77
[11.12 01:30:15.298] INFO: NodeId: Node-1
[11.12 01:30:15.298] INFO: Head-NodeId: Node-1
[11.12 01:30:15.299] INFO: CPU usage: (P/S) 3.21/4.27/100%
[11.12 01:30:15.299] INFO: Node services memory allocation (U/R/M): 768/768/14000 MB
[11.12 01:30:15.299] INFO: Threads: 37
[11.12 01:30:15.299] INFO: Heap usage: 44/256MB
[11.12 01:30:15.299] INFO: JVM: Private Build 17 (OpenJDK 64-Bit Server VM 17.0.5+8-Ubuntu-2ubuntu122.04)
[11.12 01:30:15.300] INFO: Update Repo: CloudNetService/launchermeta, Update Branch: beta
[11.12 01:30:15.300] INFO:  ```

### Other

This also happens with the CloudNet-Bridge module.

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.
```[tasklist]
### Tasks
```

**Comment by 0utplay** [comment]
Can you reproduce this with paper?

**Comment by Tiiita** [comment]
Wdym? Like it ran on paper.

**Comment by 0utplay** [comment]
Working fine with paper, looks like UniverseSpigot is doing something there.
See
https://discord.com/channels/325362837184577536/818777626663321671/1185575099202535547
