### ISSUE TITLE
cannot start cloudnet and services

### ISSUE THREAD

**Issue by 011248163264** [CloudNetService/CloudNet-v3#1346]
### Stacktrace

```
[28.12 18:41:04.353] INFO: Module eu.cloudnetservice.cloudnet.modules:CloudNet-NPCs:1.0 is being started...
[28.12 18:41:05.044] WARNING: Unable to download ProtocolLib!java.io.FileNotFoundException: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/artifact/target/ProtocolLib.jar
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1920)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
        at eu.cloudnetservice.cloudnet.ext.npcs.node.listener.IncludePluginListener.downloadProtocolLib(IncludePluginListener.java:62)
        at eu.cloudnetservice.cloudnet.ext.npcs.node.listener.IncludePluginListener.<init>(IncludePluginListener.java:45)
        at eu.cloudnetservice.cloudnet.ext.npcs.node.CloudNetNPCModule.registerListeners(CloudNetNPCModule.java:82)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at de.dytanic.cloudnet.driver.module.DefaultModuleWrapper.fireTasks(DefaultModuleWrapper.java:290)
        at de.dytanic.cloudnet.driver.module.DefaultModuleWrapper.startModule(DefaultModuleWrapper.java:226)
        at de.dytanic.cloudnet.CloudNet.startModules(CloudNet.java:1002)
        at de.dytanic.cloudnet.CloudNet.start(CloudNet.java:319)
        at de.dytanic.cloudnet.Main.main(Main.java:59)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at de.dytanic.cloudnet.launcher.CloudNetLauncher.lambda$startApplication$4(CloudNetLauncher.java:324)
        at java.base/java.lang.Thread.run(Thread.java:829)

[28.12 18:41:05.098] INFO: Module de.dytanic.cloudnet.modules:CloudNet-Report:1.1 is being started...
```

### Actions to reproduce

installed a fresh debian 11 netinstall with java 11
cloudnet is also installed but after the setup the error is showing and the services are not online on port 25565

### CloudNet version

@3.4.5-RELEASE-0f8f0d7

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by 0utplay** [comment]
The stacktrace you provided is just about protocollib not being downloaded. That has nothing to do with the service issue.
The output of the `ser list` command be great.

Furthermore I would suggest that you join our discord.

**Comment by 011248163264** [comment]
there is no firewall running, the server has internet connection, the client can connect to other minecraftservers.

mc@3.4.5-RELEASE-0f8f0d7 => ser list
[29.12 12:43:45.344] COMMAND: 7806e4b0 | Name: Lobby-1 | Node: Node-1 | Status: RUNNING | Address: 192.168.1.40:44955 | Not Connected
[29.12 12:43:45.348] COMMAND: b434d8ad | Name: Proxy-1 | Node: Node-1 | Status: RUNNING | Address: 192.168.1.40:25565 | Not Connected
[29.12 12:43:45.349] COMMAND: => Showing 2 service(s); Online: 0; Ingame: 0

**Comment by 011248163264** [comment]
there is no firewall running, the server has internet connection

**Comment by 0utplay** [comment]
Please provide your config.json located in the main directory where cloudnet is installed

**Comment by 011248163264** [comment]
the server ip is 192.168.1.40 and the client ip is 192.168.1.140
its a default installation via the start script on the first startup

{
  "identity": {
    "uniqueId": "Node-1",
    "listeners": [
      {
        "host": "0.0.0.0",
        "port": 1410
      }
    ],
    "properties": {}
  },
  "ipWhitelist": [
    "192.168.1.40",
    "192.168.1.111",
    "0:0:0:0:0:0:0:1%lo",
    "127.0.1.1",
    "127.0.0.1",
    "fe80:0:0:0:be24:11ff:fe48:f118%ens18",
    "0.0.0.0"
  ],
  "cluster": {
    "clusterId": "c602f7c6-f8f7-4f39-9250-5954aabb64da",
    "nodes": []
  },
  "maxCPUUsageToStartServices": 100.0,
  "parallelServiceStartSequence": true,
  "runBlockedServiceStartTryLaterAutomatic": true,
  "maxMemory": 5896,
  "maxServiceConsoleLogCacheSize": 64,
  "printErrorStreamLinesFromServices": true,
  "defaultJVMFlags": "DYTANIC",
  "jvmCommand": "java",
  "processTerminationTimeoutSeconds": 5,
  "hostAddress": "0.0.0.0",
  "connectHostAddress": "0.0.0.0",
  "httpListeners": [
    {
      "host": "0.0.0.0",
      "port": 2812
    }
  ],
  "clientSslConfig": {
    "enabled": false,
    "clientAuth": false,
    "trustCertificatePath": null,
    "certificatePath": "local/certificate.pem",
    "privateKeyPath": "local/privateKey.key"
  },
  "serverSslConfig": {
    "enabled": false,
    "clientAuth": false,
    "trustCertificatePath": null,
    "certificatePath": "local/certificate.pem",
    "privateKeyPath": "local/privateKey.key"
  },
  "webSslConfig": {
    "enabled": false,
    "clientAuth": false,
    "trustCertificatePath": null,
    "certificatePath": "local/certificate.pem",
    "privateKeyPath": "local/privateKey.key"
  }
}

**Comment by 0utplay** [comment]
You cant use 0.0.0.0 as connectHostAddress, use 127.0.0.1 there

**Comment by 011248163264** [comment]
ok i have chnaged the config:
with "host adress" i can connect but he says "could not connect to a default or fallbackserver"

{
  "identity": {
    "uniqueId": "Node-1",
    "listeners": [
      {
        "host": "127.0.1.1",
        "port": 1410
      }
    ],
    "properties": {}
  },
  "ipWhitelist": [
    "192.168.1.40",
    "0:0:0:0:0:0:0:1%lo",
    "127.0.1.1",
    "127.0.0.1",
    "fe80:0:0:0:be24:11ff:fe48:f118%ens18"
  ],
  "cluster": {
    "clusterId": "8a27d245-4a2e-4913-8629-cdbb66e1f4be",
    "nodes": []
  },
  "maxCPUUsageToStartServices": 100.0,
  "parallelServiceStartSequence": true,
  "runBlockedServiceStartTryLaterAutomatic": true,
  "maxMemory": 5896,
  "maxServiceConsoleLogCacheSize": 64,
  "printErrorStreamLinesFromServices": true,
  "defaultJVMFlags": "DYTANIC",
  "jvmCommand": "java",
  "processTerminationTimeoutSeconds": 5,
  "hostAddress": "192.168.1.40",
  "connectHostAddress": "127.0.1.1",
  "httpListeners": [
    {
      "host": "127.0.1.1",
      "port": 2812
    }
  ],
  "clientSslConfig": {
    "enabled": false,
    "clientAuth": false,
    "trustCertificatePath": null,
    "certificatePath": "local/certificate.pem",
    "privateKeyPath": "local/privateKey.key"
  },
  "serverSslConfig": {
    "enabled": false,
    "clientAuth": false,
    "trustCertificatePath": null,
    "certificatePath": "local/certificate.pem",
    "privateKeyPath": "local/privateKey.key"
  },
  "webSslConfig": {
    "enabled": false,
    "clientAuth": false,
    "trustCertificatePath": null,
    "certificatePath": "local/certificate.pem",
    "privateKeyPath": "local/privateKey.key"
  }
}

**Comment by 0utplay** [comment]
Which version are u using to connect?

**Comment by 011248163264** [comment]
spigot 1.16.5 on server and client 1.16.5

**Comment by 011248163264** [comment]
[29.12 15:21:54.941] INFO: CloudService [uniqueId=d0e0c5e9-f517-4ca9-b7ef-0e2555a1502f task=Proxy name=Proxy-1] is being prepared...
[29.12 15:21:55.167] INFO: CloudService [uniqueId=d0e0c5e9-f517-4ca9-b7ef-0e2555a1502f task=Proxy name=Proxy-1] is started...
[29.12 15:21:55.275] INFO: CloudService [uniqueId=2344c70a-e8bc-4f92-a85f-4084c40f8201 task=Lobby name=Lobby-1] is being prepared...
[29.12 15:21:55.773] INFO: CloudService [uniqueId=2344c70a-e8bc-4f92-a85f-4084c40f8201 task=Lobby name=Lobby-1] is started...
[29.12 15:21:57.929] INFO: CloudService [uniqueId=d0e0c5e9-f517-4ca9-b7ef-0e2555a1502f task=Proxy name=Proxy-1] was successfully connected to the channel [serverAddress=127.0.1.1:1410 clientAddress=127.0.0.1:55426]
[29.12 15:21:58.641] INFO: CloudService [uniqueId=2344c70a-e8bc-4f92-a85f-4084c40f8201 task=Lobby name=Lobby-1] was successfully connected to the channel [serverAddress=127.0.1.1:1410 clientAddress=127.0.0.1:55436]
[29.12 15:22:12.767] INFO: Login Request from the identity 56e7f07f-1f50-46c2-9fbb-f0eca5b9737e:DosePlay on the proxy Proxy-1
[29.12 15:22:12.921] INFO: Login from the identity 56e7f07f-1f50-46c2-9fbb-f0eca5b9737e:DosePlay on proxy Proxy-1 was successful
[29.12 15:22:13.218] INFO: The identity 56e7f07f-1f50-46c2-9fbb-f0eca5b9737e:DosePlay on the proxy Proxy-1 has left the network

**Comment by 0utplay** [comment]
Please provide the log of both the service and the proxy

**Comment by 011248163264** [comment]
ok the service is running it was the server the map generation was slow.
