### ISSUE TITLE
issues with PlayerManager 

### ISSUE THREAD

**Issue by Ente3** [CloudNetService/CloudNet-v3#1468]
### Stacktrace

```
[23:41:52] [Server thread/ERROR]: Error occurred while enabling CloudNet-Signs v4.0.0-RC10 (Is it up to date?)

dev.derklaro.aerogel.AerogelException: Unable to construct requested value constructor BukkitSignManagement((Object[])Object)

Caused by: java.lang.NullPointerException: playerManager is marked non-null but is null

    at eu.cloudnetservice.modules.signs.platform.bukkit.BukkitSignManagement.<init>(BukkitSignManagement.java:59) ~[cloudnet-signs.jar:?]

    at dev.derklaro.aerogel.internal.util.MethodHandleUtil.invokeConstructor(MethodHandleUtil.java:88) ~[aerogel-2.1.0.jar:?]

    at dev.derklaro.aerogel.internal.binding.constructors.ConstructingBindingConstructor.lambda$constructProvider$0(ConstructingBindingConstructor.java:92) ~[aerogel-2.1.0.jar:?]

    at dev.derklaro.aerogel.internal.provider.FunctionalContextualProvider.get(FunctionalContextualProvider.java:74) ~[aerogel-2.1.0.jar:?]

    at dev.derklaro.aerogel.util.Scopes$SingletonContextualProvider.get(Scopes.java:96) ~[aerogel-2.1.0.jar:?]

    at dev.derklaro.aerogel.internal.context.DefaultInjectionContext.resolveInstance(DefaultInjectionContext.java:388) ~[aerogel-2.1.0.jar:?]

    at dev.derklaro.aerogel.internal.invoke.ParameterHelper.lambda$constructParameterSuppliers$3(ParameterHelper.java:95) ~[aerogel-2.1.0.jar:?]

    at dev.derklaro.aerogel.internal.invoke.ParameterHelper.lambda$constructParameterSuppliers$4(ParameterHelper.java:108) ~[aerogel-2.1.0.jar:?]

    at dev.derklaro.aerogel.internal.binding.constructors.ConstructingBindingConstructor.lambda$constructProvider$0(ConstructingBindingConstructor.java:91) ~[aerogel-2.1.0.jar:?]

    at dev.derklaro.aerogel.internal.provider.FunctionalContextualProvider.get(FunctionalContextualProvider.java:74) ~[aerogel-2.1.0.jar:?]

    at dev.derklaro.aerogel.util.Scopes$SingletonContextualProvider.get(Scopes.java:96) ~[aerogel-2.1.0.jar:?]

    at dev.derklaro.aerogel.internal.context.DefaultInjectionContext.resolveInstance(DefaultInjectionContext.java:388) ~[aerogel-2.1.0.jar:?]

    at dev.derklaro.aerogel.internal.invoke.ParameterHelper.lambda$constructParameterSuppliers$3(ParameterHelper.java:95) ~[aerogel-2.1.0.jar:?]

    at dev.derklaro.aerogel.internal.invoke.ParameterHelper.lambda$constructParameterSuppliers$4(ParameterHelper.java:108) ~[aerogel-2.1.0.jar:?]

    at dev.derklaro.aerogel.internal.binding.constructors.ConstructingBindingConstructor.lambda$constructProvider$0(ConstructingBindingConstructor.java:91) ~[aerogel-2.1.0.jar:?]

    at dev.derklaro.aerogel.internal.provider.FunctionalContextualProvider.get(FunctionalContextualProvider.java:74) ~[aerogel-2.1.0.jar:?]

    at dev.derklaro.aerogel.util.Scopes$SingletonContextualProvider.get(Scopes.java:96) ~[aerogel-2.1.0.jar:?]

    at dev.derklaro.aerogel.internal.context.DefaultInjectionContext.resolveInstance(DefaultInjectionContext.java:388) ~[aerogel-2.1.0.jar:?]

    at dev.derklaro.aerogel.internal.context.util.ContextInstanceResolveHelper.resolveInstanceAndRemoveContext(ContextInstanceResolveHelper.java:95) ~[aerogel-2.1.0.jar:?]

    at dev.derklaro.aerogel.internal.context.util.ContextInstanceResolveHelper.resolveInstance(ContextInstanceResolveHelper.java:79) ~[aerogel-2.1.0.jar:?]

    at dev.derklaro.aerogel.internal.context.util.ContextInstanceResolveHelper.resolveInstance(ContextInstanceResolveHelper.java:63) ~[aerogel-2.1.0.jar:?]

    at dev.derklaro.aerogel.internal.DefaultSpecifiedInjector.instance(DefaultSpecifiedInjector.java:310) ~[aerogel-2.1.0.jar:?]

    at dev.derklaro.aerogel.internal.DefaultSpecifiedInjector.instance(DefaultSpecifiedInjector.java:292) ~[aerogel-2.1.0.jar:?]

    at eu.cloudnetservice.driver.inject.DefaultInjectionLayer.instance(DefaultInjectionLayer.java:58) ~[wrapper.jar:4.0.0-RC10-887ad7cf]

    at eu.cloudnetservice.ext.platforminject.api.defaults.BasePlatformPluginManager.constructAndLoad(BasePlatformPluginManager.java:92) ~[wrapper.jar:4.0.0-RC10-887ad7cf]

    at eu.cloudnetservice.ext.platforminject.loader.PlatformInjectSupportLoader.loadPlugin(PlatformInjectSupportLoader.java:40) ~[wrapper.jar:4.0.0-RC10-887ad7cf]

    at eu.cloudnetservice.modules.signs.platform.bukkit.GeneratedBukkitCloudNet_SignsEntrypoint.onEnable(GeneratedBukkitCloudNet_SignsEntrypoint.java:13) ~[cloudnet-signs.jar:?]

    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]

    at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[purpur-1.20.4.jar:git-Purpur-2176]

    at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2176]

    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]

    at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:653) ~[purpur-1.20.4.jar:git-Purpur-2176]

    at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:564) ~[purpur-1.20.4.jar:git-Purpur-2176]

    at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[purpur-1.20.4.jar:git-Purpur-2176]

    at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[purpur-1.20.4.jar:git-Purpur-2176]

    at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:346) ~[purpur-1.20.4.jar:git-Purpur-2176]

    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2176]

    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]

    at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Actions to reproduce

Upload the nuvotifier https://www.spigotmc.org/resources/nuvotifier.13449/
together with a plugin which uses the PlayerManager like the CloudSign-Module

### CloudNet version

V4.0.0-RC10

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by 0utplay** [comment]
Hi, please provide the full server log

**Comment by Ente3** [comment]
Hi, after some more testing, I figured out it's not by the nuvotifier.
In one of my plugins, I use the PlayerManager (```InjectionLayer.ext().instance(ServiceRegistry.class).firstProvider(PlayerManager.class).groupOnlinePlayers(group).count()```)
Maybe I did it wrong but after using the Cloud-Sings plugin as a dependency in the plugin.yml in everything is working without any issues for now

Perhaps I didn't define the PlayerManager properly before?

**Comment by 0utplay** [comment]
Perhaps you just need a depend on the bridge and not signs.

But anyway I think we can close this
