### ISSUE TITLE
Copying services to templates end as an error

### ISSUE THREAD

**Issue by JWeinelt** [CloudNetService/CloudNet-v3#1550]
### Stacktrace

```
01.12 10:19:14.643] ERROR: Exception during command execution
org.incendo.cloud.exception.CommandExecutionException: java.lang.NullPointerException: Cannot invoke "eu.cloudnetservice.common.tuple.Tuple2.first()" because "target" is null
        at org.incendo.cloud.annotations.MethodCommandExecutionHandler.executeFuture(MethodCommandExecutionHandler.java:100)
        at org.incendo.cloud.execution.ExecutionCoordinatorImpl.lambda$coordinateExecution$4(ExecutionCoordinatorImpl.java:121)
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1194)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:526)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1575)
Caused by: java.lang.NullPointerException: Cannot invoke "eu.cloudnetservice.common.tuple.Tuple2.first()" because "target" is null
        at eu.cloudnetservice.node.command.sub.ServiceCommand.copyService(ServiceCommand.java:231)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:758)
        at org.incendo.cloud.annotations.MethodCommandExecutionHandler.executeFuture(MethodCommandExecutionHandler.java:88)
        ... 6 common frames omitted
```

### Actions to reproduce

- Use RC11.1
- Try to copy a static service in a template e.g. ``/cloud ser Lobby-1 copy``
- The error will occur in the console.

### CloudNet version

root@4.0.0-RC11.1-38c60eb2 => me
[01.12 10:23:05.624] INFO :  
[01.12 10:23:05.625] INFO : CloudNet Blizzard 4.0.0-RC11.1 38c60eb2
[01.12 10:23:05.625] INFO : Discord: <https://discord.cloudnetservice.eu/>
[01.12 10:23:05.625] INFO :  
[01.12 10:23:05.626] INFO : ClusterId: b26b46c8-****-41a1-****-cd166874e3e4
[01.12 10:23:05.626] INFO : NodeId: Node-1
[01.12 10:23:05.626] INFO : Head-NodeId: Node-1
[01.12 10:23:05.626] INFO : CPU usage: (P/S) 2.95/37.92/100%
[01.12 10:23:05.626] INFO : Node services memory allocation (U/R/M): 12144/12144/18000 MB
[01.12 10:23:05.626] INFO : Threads: 57
[01.12 10:23:05.627] INFO : Heap usage: 68/256MB
[01.12 10:23:05.627] INFO : JVM: Oracle Corporation 23 (Java HotSpot(TM) 64-Bit Server VM 23.0.1+11-39)
[01.12 10:23:05.628] INFO : Update Repo: CloudNetService/launchermeta, Update Branch: beta

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by 0utplay** [comment]
Hi, can you please share `tasks task Lobby` and `ser Lobby-1`
