### ISSUE TITLE
Out of Memory nach Cluster Push all

### ISSUE THREAD

**Issue by AixMC** [CloudNetService/CloudNet-v3#235]
Nachdem der Push abgeschlossen ist kommt der Fehler, eigentlich ist aber noch eine Menge RAM frei (~12GB) ausserdem tritt der Fehler nicht auf wenn nicht alle Nodes online sind. 

`[18.02 03:43:15.115] ERROR: io.netty.handler.codec.EncoderException: java.lang.OutOfMemoryError: Direct buffer memory
[18.02 03:43:15.115] ERROR:     at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[18.02 03:43:15.115] ERROR:     at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:716)
[18.02 03:43:15.115] ERROR:     at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:708)
[18.02 03:43:15.115] ERROR:     at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:791)
[18.02 03:43:15.115] ERROR:     at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:701)
[18.02 03:43:15.115] ERROR:     at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[18.02 03:43:15.115] ERROR:     at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:716)
[18.02 03:43:15.115] ERROR:     at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:763)
[18.02 03:43:15.115] ERROR:     at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:789)
[18.02 03:43:15.115] ERROR:     at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:757)
[18.02 03:43:15.115] ERROR:     at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1031)
[18.02 03:43:15.115] ERROR:     at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:310)
[18.02 03:43:15.115] ERROR:     at de.dytanic.cloudnet.driver.network.netty.NettyNetworkChannel.sendPacket0(NettyNetworkChannel.java:79)
[18.02 03:43:15.115] ERROR:     at de.dytanic.cloudnet.driver.network.netty.NettyNetworkChannel.lambda$sendPacket$1(NettyNetworkChannel.java:56)
[18.02 03:43:15.115] ERROR:     at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[18.02 03:43:15.115] ERROR:     at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:405)
[18.02 03:43:15.115] ERROR:     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:338)
[18.02 03:43:15.115] ERROR:     at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
[18.02 03:43:15.115] ERROR:     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[18.02 03:43:15.115] ERROR:     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[18.02 03:43:15.115] ERROR:     at java.base/java.lang.Thread.run(Thread.java:834)
[18.02 03:43:15.115] ERROR: Caused by: java.lang.OutOfMemoryError: Direct buffer memory
[18.02 03:43:15.115] ERROR:     at java.base/java.nio.Bits.reserveMemory(Bits.java:175)
[18.02 03:43:15.115] ERROR:     at java.base/java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:118)
[18.02 03:43:15.115] ERROR:     at java.base/java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:317)
[18.02 03:43:15.115] ERROR:     at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:772)
[18.02 03:43:15.115] ERROR:     at io.netty.buffer.PoolArena$DirectArena.newUnpooledChunk(PoolArena.java:762)
[18.02 03:43:15.115] ERROR:     at io.netty.buffer.PoolArena.allocateHuge(PoolArena.java:260)
[18.02 03:43:15.115] ERROR:     at io.netty.buffer.PoolArena.allocate(PoolArena.java:232)
[18.02 03:43:15.115] ERROR:     at io.netty.buffer.PoolArena.reallocate(PoolArena.java:400)
[18.02 03:43:15.115] ERROR:     at io.netty.buffer.PooledByteBuf.capacity(PooledByteBuf.java:120)
[18.02 03:43:15.115] ERROR:     at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:295)
[18.02 03:43:15.115] ERROR:     at io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:274)
[18.02 03:43:15.115] ERROR:     at de.dytanic.cloudnet.driver.network.netty.NettyPacketLengthSerializer.encode(NettyPacketLengthSerializer.java:21)
[18.02 03:43:15.115] ERROR:     at de.dytanic.cloudnet.driver.network.netty.NettyPacketLengthSerializer.encode(NettyPacketLengthSerializer.java:11)
[18.02 03:43:15.115] ERROR:     at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[18.02 03:43:15.115] ERROR:     ... 20 more`

**Comment by derklaro** [comment]
Dieser Fehler ist bekannt und schon Teil des übernächsten Releases.
