### ISSUE TITLE
Error when try to add new template using CloudNetDriver

### ISSUE THREAD

**Issue by chitkiu** [CloudNetService/CloudNet-v3#256]
**Describe the bug**<br>
Exeption when I try to add new ServiceTemplate using CloudNetDriver API
**Steps for reproducing**<br>

Steps to reproduce the exception:
1. Get CloudServiceProvider by service name
2. Call method '#addServiceTemplate(ServiceTemplate)'
3. See exception
[08.04 23:11:26.584] ERROR: java.lang.ClassCastException: de.dytanic.cloudnet.driver.service.ServiceTemplate cannot be cast to de.dytanic.cloudnet.driver.service.ServiceRemoteInclusion
[08.04 23:11:26.584] ERROR:     at de.dytanic.cloudnet.network.listener.PacketClientSyncAPIPacketListener.handle0(PacketClientSyncAPIPacketListener.java:246)
[08.04 23:11:26.584] ERROR:     at de.dytanic.cloudnet.network.listener.PacketClientSyncAPIPacketListener.handle(PacketClientSyncAPIPacketListener.java:23)
[08.04 23:11:26.584] ERROR:     at de.dytanic.cloudnet.driver.network.protocol.DefaultPacketListenerRegistry.handlePacket(DefaultPacketListenerRegistry.java:118)
[08.04 23:11:26.584] ERROR:     at de.dytanic.cloudnet.driver.network.netty.NettyNetworkServerHandler.lambda$channelRead0$0(NettyNetworkServerHandler.java:67)
[08.04 23:11:26.584] ERROR:     at de.dytanic.cloudnet.common.concurrent.DefaultScheduledTask.call(DefaultScheduledTask.java:140)
[08.04 23:11:26.584] ERROR:     at de.dytanic.cloudnet.common.concurrent.DefaultTaskScheduler$Worker.run0(DefaultTaskScheduler.java:306)
[08.04 23:11:26.584] ERROR:     at de.dytanic.cloudnet.common.concurrent.DefaultTaskScheduler$Worker.run(DefaultTaskScheduler.java:277)

**Expected behavior**
CloudNet should add ServiceTemplate without any issue

**Please provide us information about your environment and used assets**
 OS: Ubuntu 18.04 LTS
 Version: CloudNEt 3.2.2-RELEASE

**Additional context**
I think, that someone made mistake in this part of code https://github.com/CloudNetService/CloudNet-v3/blob/a6f63913c18358d68cd53c207de8c506ac353a91/cloudnet/src/main/java/de/dytanic/cloudnet/network/listener/PacketClientSyncAPIPacketListener.java#L246

**Comment by derrop** [comment]
This is already fixed on the development branch
