### ISSUE TITLE
Nukkit Server startet nicht

### ISSUE THREAD

**Issue by Supermann77** [CloudNetService/CloudNet-v3#276]
**Description of the bug:**

Wenn ich versuche die Cloud zu starten mit meinem Nukkit Server, passiert diesen Fehler: 
Der Server ist im PREPARED Status. Voher hat es problemlos funktioniert, jedoch weiß ich nicht mehr weiter.

2020-05-25 17:58:03.717 [Application-Thread] INFO  - Loading §aserver.properties§f ...
2020-05-25 17:58:03.722 [Application-Thread] INFO  - Selected English (eng) as the base language
2020-05-25 17:58:03.722 [Application-Thread] INFO  - Starting Minecraft: BE server version §bv1.14.60§r
2020-05-25 17:58:03.724 [Application-Thread] INFO  - Selected Zlib Provider: 2 (cn.nukkit.utils.ZlibThreadLocal)
2020-05-25 17:58:03.741 [Application-Thread] INFO  - Opening server on 217.182.197.206:44957
2020-05-25 17:58:03.749 [Application-Thread] INFO  - This server is running Nukkit version §egit-c43d425§f "§b§f" (API 1.0.9)
2020-05-25 17:58:03.750 [Application-Thread] INFO  - Nukkit is distributed under the LGPL License
2020-05-25 17:58:03.757 [Application-Thread] ERROR - Throwing
java.lang.NoClassDefFoundError: Could not initialize class co.aikar.timings.Timings
	at cn.nukkit.command.Command.<init>(Command.java:70) ~[nukkit.jar:?]
	at cn.nukkit.command.defaults.VanillaCommand.<init>(VanillaCommand.java:24) ~[nukkit.jar:?]
	at cn.nukkit.command.defaults.VersionCommand.<init>(VersionCommand.java:19) ~[nukkit.jar:?]
	at cn.nukkit.command.SimpleCommandMap.setDefaultCommands(SimpleCommandMap.java:32) ~[nukkit.jar:?]
	at cn.nukkit.command.SimpleCommandMap.<init>(SimpleCommandMap.java:28) ~[nukkit.jar:?]
	at cn.nukkit.Server.<init>(Server.java:452) ~[nukkit.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:112) ~[nukkit.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_221]
	at de.dytanic.cloudnet.wrapper.Wrapper.lambda$startApplication$5(Wrapper.java:510) ~[wrapper.jar:3.4.0-SNAPSHOT-00fd77b]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
2020-05-25 17:58:03.760 [Application-Thread] INFO  - Stopping other threads

**Steps to reproduce this bug:**

**Expected behavior:**

Normalerweise sollte der Server starten. Der minServiceCount ist bei 1

**Screenshots:**

**Environment and used hardware:**

**Additional context (optional):**

**Comment by juliarn** [comment]
Wenn Services nur prepared sind obwohl der minServiceCount nicht erfüllt ist liegt das meistens daran, dass kein RAM mehr frei ist. Wie sieht die Task-Datei vom Nukkit Service aus und was steht beim Command ``me``?

**Comment by Supermann77** [comment]
Hallo @juliarn,

Der Server sollte genügend Ram haben.
Hier ist die Task-Datei: http://prntscr.com/snj2hw

Das steht bei me: http://prntscr.com/snj21f

**Comment by juliarn** [comment]
Es sind noch ca. 4GB frei, dein Server will aber 8GB nutzen. Die cloud hält für jeden Service die maxHeapMemory frei.
Deswegen lässt die Cloud ihn auch auf prepared und startet ihn nicht.

**Comment by Supermann77** [comment]
achso danke

**Comment by juliarn** [comment]
Gerne ♥️
