### ISSUE TITLE
SyncProxyConfiguration.getConfigurationFromNode() throws NoSuchElementException

### ISSUE THREAD

**Issue by RandomModderJDK** [CloudNetService/CloudNet-v3#375]
**Description of the bug:**
I just discovered that if you want to reconstruct ServerSPExample.java it throws an NoSuchElementException.

**Steps to reproduce this bug:**

**Expected behavior:**

I thought I could use these Methods then.

**Screenshots:**

**Environment and used hardware:**

**Additional context (optional):**

**Comment by derklaro** [comment]
Please attach the exception

**Comment by RandomModderJDK** [comment]
> 
> 
> Issue-Label Bot is automatically applying the label `bug` to this issue, with a confidence of 0.96. Please mark this comment with 👍 or 👎 to give our bot feedback!
> 
> Links: [app homepage](https://github.com/marketplace/issue-label-bot), [dashboard](https://mlbot.net/data/CloudNetService/CloudNet-v3) and [code](https://github.com/hamelsmu/MLapp) for this bot.

**Comment by RandomModderJDK** [comment]
```
java.util.NoSuchElementException
[24.10 20:59:22.059] ERROR:     at java.base/java.util.concurrent.ConcurrentLinkedQueue$Itr.next(ConcurrentLinkedQueue.java:777)
[24.10 20:59:22.059] ERROR:     at java.base/java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1049)
[24.10 20:59:22.059] ERROR:     at de.dytanic.cloudnet.ext.syncproxy.configuration.SyncProxyConfiguration.getConfigurationFromNode(SyncProxyConfiguration.java:24)
[24.10 20:59:22.059] ERROR:     at eu.thesystems.cloudnet.webinterface.webhandler.NetworkInfoHttpHandler.handle(NetworkInfoHttpHandler.java:25)
[24.10 20:59:22.059] ERROR:     at de.dytanic.cloudnet.driver.network.netty.NettyHttpServerHandler.handleMessage0(NettyHttpServerHandler.java:149)
[24.10 20:59:22.060] ERROR:     at de.dytanic.cloudnet.driver.network.netty.NettyHttpServerHandler.handleMessage(NettyHttpServerHandler.java:83)
[24.10 20:59:22.060] ERROR:     at de.dytanic.cloudnet.driver.network.netty.NettyHttpServerHandler.channelRead0(NettyHttpServerHandler.java:56)
[24.10 20:59:22.060] ERROR:     at de.dytanic.cloudnet.driver.network.netty.NettyHttpServerHandler.channelRead0(NettyHttpServerHandler.java:12)
[24.10 20:59:22.060] ERROR:     at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
[24.10 20:59:22.060] ERROR:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
[24.10 20:59:22.060] ERROR:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
[24.10 20:59:22.060] ERROR:     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
[24.10 20:59:22.060] ERROR:     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[24.10 20:59:22.060] ERROR:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
[24.10 20:59:22.060] ERROR:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
[24.10 20:59:22.060] ERROR:     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
[24.10 20:59:22.060] ERROR:     at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
[24.10 20:59:22.060] ERROR:     at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
[24.10 20:59:22.060] ERROR:     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
[24.10 20:59:22.060] ERROR:     at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
[24.10 20:59:22.060] ERROR:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
[24.10 20:59:22.060] ERROR:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
[24.10 20:59:22.060] ERROR:     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
[24.10 20:59:22.060] ERROR:     at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
[24.10 20:59:22.060] ERROR:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
[24.10 20:59:22.060] ERROR:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
[24.10 20:59:22.060] ERROR:     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
[24.10 20:59:22.060] ERROR:     at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
[24.10 20:59:22.060] ERROR:     at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682)
[24.10 20:59:22.060] ERROR:     at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:617)
[24.10 20:59:22.060] ERROR:     at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:534)
[24.10 20:59:22.060] ERROR:     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
[24.10 20:59:22.060] ERROR:     at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
[24.10 20:59:22.060] ERROR:     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[24.10 20:59:22.060] ERROR:     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[24.10 20:59:22.060] ERROR:     at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by einrobin** [comment]
This method is only intended to be used from a server (e.g. spigot, nukkit), to use it from a Node, you can use the CloudNetSyncProxyModule class

**Comment by RandomModderJDK** [comment]
Oh ok, yeah then thanks
