### ISSUE TITLE
CloudNet not working on aarch64 architecture

### ISSUE THREAD

**Issue by DSeeLP** [CloudNetService/CloudNet-v3#413]
**Description of the bug:**

When you try to start CloudNet on an machine that uses aarch64 architecture, for example the Raspberry 4 with Raspberry PI OS 64bit Beta it fails to start with this error.
```
Running CloudNet launcher created with 3.3.0-RELEASE-521c3bc...
Using installed CloudNet version 3.3.0-RELEASE
Starting CloudNet...
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at de.dytanic.cloudnet.launcher.CloudNetLauncher.lambda$startApplication$4(CloudNetLauncher.java:297)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no jansi in java.library.path: [/usr/java/packages/lib, /usr/lib/aarch64-linux-gnu/jni, /lib/aarch64-linux-gnu, /usr/lib/aarch64-linux-gnu, /usr/lib/jni, /lib, /usr/lib], /tmp/libjansi-64-1465338968388413597.so: /tmp/libjansi-64-1465338968388413597.so: cannot open shared object file: No such file or directory (Possible cause: can't load AMD 64-bit .so on a AARCH64-bit platform)]
        at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:182)
        at org.fusesource.hawtjni.runtime.Library.load(Library.java:140)
        at org.fusesource.jansi.internal.CLibrary.<clinit>(CLibrary.java:42)
        at org.fusesource.jansi.AnsiConsole.wrapOutputStream(AnsiConsole.java:48)
        at org.fusesource.jansi.AnsiConsole.<clinit>(AnsiConsole.java:38)
        at de.dytanic.cloudnet.console.JLine2Console.<init>(JLine2Console.java:45)
        at de.dytanic.cloudnet.Main.main(Main.java:24)
        ... 6 more
```

Output of uname -a:
```
Linux raspberrypi 5.10.17-v8+ #1403 SMP PREEMPT Mon Feb 22 11:37:54 GMT 2021 aarch64 GNU/Linux
```

**Steps to reproduce this bug:**
Launch CloudNet on an machine that uses the aarch64 architecture.

**Expected behavior:**
It should start without any errors.

**Environment and used hardware:**
Device: Raspberry Pi 4B Revision 1.2 4GB
OS:  Raspberry PI OS 64bit Beta
Version: CloudNet 3.3

**Comment by juliarn** [comment]
Hey, this works in the 3.4 Snapshot version of CloudNet, found on the ``development`` branch. Builds can be found here: https://ci.cloudnetservice.eu/job/CloudNetService/job/CloudNet-v3/job/development/lastSuccessfulBuild/artifact/ or just enable the option "use-snapshots" in the launcher.cnl file and restart the cloud.

**Comment by DSeeLP** [comment]
Ok, updating to the Snapshot 3.4 fixed the issue, so i will close this issue now.
