### ISSUE TITLE
Some events seem to fire twice for no reason

### ISSUE THREAD

**Issue by Sneakometer** [CloudNetService/CloudNet-v3#460]
**Description of the bug:**
So we recently planned to switch to cloudnet with our server network for several reasons.
We are now running a test server with a very basic cloudnet setup (3.3, paper, waterfall)
But after some time the bungeecord proxy starts to throw exceptions that are not related to our plugins and never occoured before:
```
[01.05 17:00:32.867] INFO: [Proxy-1] [17:00:32 WARN] [io.netty.util.concurrent.AbstractEventExecutor]: A task raised an exception. Task: net.md_5.bungee.connection.InitialHandler$6$1@307f1737
[01.05 17:00:32.867] INFO: [Proxy-1] java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[01.05 17:00:32.867] INFO: [Proxy-1]  at java.util.ArrayList.rangeCheck(ArrayList.java:659) ~[?:1.8.0_291]
[01.05 17:00:32.867] INFO: [Proxy-1]  at java.util.ArrayList.get(ArrayList.java:435) ~[?:1.8.0_291]
[01.05 17:00:32.867] INFO: [Proxy-1]  at net.md_5.bungee.api.config.ListenerInfo.getDefaultServer(ListenerInfo.java:91) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:f2d67ca:394]
[01.05 17:00:32.867] INFO: [Proxy-1]  at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:566) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:f2d67ca:394]
[01.05 17:00:32.867] INFO: [Proxy-1]  at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:f2d67ca:394]
[01.05 17:00:32.867] INFO: [Proxy-1]  at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:f2d67ca:394]
[01.05 17:00:32.867] INFO: [Proxy-1]  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:f2d67ca:394]
[01.05 17:00:32.867] INFO: [Proxy-1]  at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:f2d67ca:394]
[01.05 17:00:32.867] INFO: [Proxy-1]  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:f2d67ca:394]
[01.05 17:00:32.867] INFO: [Proxy-1]  at java.lang.Thread.run(Thread.java:748) [?:1.8.0_291]
```
Nobody can login to the server at that point until the proxy is stopped and restarted.

**Steps to reproduce this bug:**
Basic cloudnet setup with waterfall as proxy, then starting and stopping various minecraft services and eventually nobody can join and it prints the exception above to the proxy log.

Steps to reproduce the exception:
1. Join through the waterfall proxy.

**Expected behavior:**
To not stop working at some point.

**Environment and used hardware:**
Debian 10
java 8
Cloudnet v3.3
Waterfall latest
Paperspigot

**Comment by juliarn** [comment]
Hey, this should not be related to breaking the event system, this error usually occurs when there is no fallback available. In 3.3, there was a small issue which might be the cause of this. You can try to switch over to the 3.4 snapshot (found on the development branch), it should work then. To get it, you can enable the option "use-snapshots" in the launcher.cnl file and restart.

**Comment by Sneakometer** [comment]
Okay got it. It's now working. Thanks.
Issue was v3.3

**Comment by Sneakometer** [comment]
Okay now on 3.4 Snapshot there is another issue.
The `CloudServiceStartEvent` fires twice for each started service. Is this a known bug?

// Edit
`CloudServiceStopEvent` also appears to be affected.

**Comment by juliarn** [comment]
Are you listening to this event from a module or from the wrapper (a bukkit plugin for example)?

**Comment by Sneakometer** [comment]
From a Bukkit plugin.

The listener is only registered once in the bukkit plugins onEnable()

**Comment by derklaro** [comment]
Can't confirm this issue.
