### ISSUE TITLE
java.lang.NullPointerException in BungeeCord

### ISSUE THREAD

**Issue by Sneakometer** [CloudNetService/CloudNet-v3#482]
A bug where no players can join the network.
When this happens, no players can join. Everytime someone wants to join the proxy, this exception is printed.
Occours after some hours to days of running cloudnet.

```
[25.05 01:23:57.489] INFO: [Proxy-1] [01:23:56 WARN] [io.netty.util.concurrent.AbstractEventExecutor]: A task raised an exception. Task: net.md_5.bungee.connection.InitialHandler$6$1@1adbcb73
[25.05 01:23:57.489] INFO: [Proxy-1] java.lang.NullPointerException: info
[25.05 01:23:57.489] INFO: [Proxy-1]  at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
[25.05 01:23:57.489] INFO: [Proxy-1]  at net.md_5.bungee.UserConnection.connect(UserConnection.java:273) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
[25.05 01:23:57.489] INFO: [Proxy-1]  at net.md_5.bungee.UserConnection.connect(UserConnection.java:264) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
[25.05 01:23:57.489] INFO: [Proxy-1]  at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:569) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
[25.05 01:23:57.489] INFO: [Proxy-1]  at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
[25.05 01:23:57.489] INFO: [Proxy-1]  at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
[25.05 01:23:57.489] INFO: [Proxy-1]  at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
[25.05 01:23:57.489] INFO: [Proxy-1]  at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
[25.05 01:23:57.489] INFO: [Proxy-1]  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
[25.05 01:23:57.489] INFO: [Proxy-1]  at java.lang.Thread.run(Thread.java:748) [?:1.8.0_291]

```
I can't get any useful information from this stacktrace nor do i know what causes it yet.

I suspect this being a cloudnet issue because we where running the exact same setup and plugins for month without cloudnet with no issues.

**Environment:**
- Cloudnet v3.4
- Java 8
- Debian 10

**Comment by derklaro** [comment]
Hello, is it a custom waterfall build or which branch are you using cause i can't return to your revision `9965730` on master.

**Comment by Sneakometer** [comment]
I was running the test jar from Janmm14 with some DoS mitigations from https://github.com/PaperMC/Waterfall/pull/609
I now switched to the latest official build (#643) to see if this is a compatibility issue with that particular patch.

// Edit
Searching the logs i found that the first exceptions differs from the resulting errors:
```
[19:39:01] [pool-3-thread-3/ERROR]: de.dytanic.cloudnet.driver.event.EventListenerException: Error while invoking event listener handle in class de.dytanic.cloudnet.ext.bridge.bungee.listener.BungeeCloudNetListener
[19:39:01] [pool-3-thread-3/ERROR]: 	at de.dytanic.cloudnet.driver.event.DefaultRegisteredEventListener.fireEvent(DefaultRegisteredEventListener.java:55)
[19:39:01] [pool-3-thread-3/ERROR]: 	at de.dytanic.cloudnet.driver.event.DefaultEventManager.fireEvent(DefaultEventManager.java:123)
[19:39:01] [pool-3-thread-3/ERROR]: 	at de.dytanic.cloudnet.driver.event.DefaultEventManager.fireEvent(DefaultEventManager.java:113)
[19:39:01] [pool-3-thread-3/ERROR]: 	at de.dytanic.cloudnet.driver.event.DefaultEventManager.callEvent(DefaultEventManager.java:100)
[19:39:01] [pool-3-thread-3/ERROR]: 	at de.dytanic.cloudnet.driver.event.IEventManager.callEvent(IEventManager.java:24)
[19:39:01] [pool-3-thread-3/ERROR]: 	at de.dytanic.cloudnet.wrapper.network.listener.PacketServerServiceInfoPublisherListener.invoke0(PacketServerServiceInfoPublisherListener.java:45)
[19:39:01] [pool-3-thread-3/ERROR]: 	at de.dytanic.cloudnet.wrapper.network.listener.PacketServerServiceInfoPublisherListener.handle(PacketServerServiceInfoPublisherListener.java:36)
[19:39:01] [pool-3-thread-3/ERROR]: 	at de.dytanic.cloudnet.driver.network.protocol.DefaultPacketListenerRegistry.handlePacket(DefaultPacketListenerRegistry.java:133)
[19:39:01] [pool-3-thread-3/ERROR]: 	at de.dytanic.cloudnet.driver.network.protocol.DefaultPacketListenerRegistry.handlePacket(DefaultPacketListenerRegistry.java:127)
[19:39:01] [pool-3-thread-3/ERROR]: 	at de.dytanic.cloudnet.driver.network.netty.NettyNetworkHandler.lambda$channelRead0$0(NettyNetworkHandler.java:52)
[19:39:01] [pool-3-thread-3/ERROR]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[19:39:01] [pool-3-thread-3/ERROR]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[19:39:01] [pool-3-thread-3/ERROR]: 	at java.lang.Thread.run(Thread.java:748)
[19:39:01] [pool-3-thread-3/ERROR]: Caused by: java.lang.ArrayIndexOutOfBoundsException: 96
[19:39:01] [pool-3-thread-3/ERROR]: 	at gnu.trove.map.hash.TCustomHashMap.rehash(TCustomHashMap.java:407)
[19:39:01] [pool-3-thread-3/ERROR]: 	at gnu.trove.impl.hash.THash.postInsertHook(THash.java:417)
[19:39:01] [pool-3-thread-3/ERROR]: 	at gnu.trove.map.hash.TCustomHashMap.doPut(TCustomHashMap.java:182)
[19:39:01] [pool-3-thread-3/ERROR]: 	at gnu.trove.map.hash.TCustomHashMap.put(TCustomHashMap.java:148)
[19:39:01] [pool-3-thread-3/ERROR]: 	at de.dytanic.cloudnet.ext.bridge.bungee.listener.BungeeCloudNetListener.handle(BungeeCloudNetListener.java:34)
[19:39:01] [pool-3-thread-3/ERROR]: 	at GeneratedListenerInvoker_d4c3fb3511ec4a3e9e1d3ce7d14fe9ee.invoke(GeneratedListenerInvoker_d4c3fb3511ec4a3e9e1d3ce7d14fe9ee.java)
[19:39:01] [pool-3-thread-3/ERROR]: 	at de.dytanic.cloudnet.driver.event.DefaultRegisteredEventListener.fireEvent(DefaultRegisteredEventListener.java:53)
[19:39:01] [pool-3-thread-3/ERROR]: 	... 12 more
[19:39:02] [Netty Worker IO Thread #24/INFO]: [/********:50538] <-> InitialHandler has pinged
[19:39:02] [Netty Worker IO Thread #24/ERROR]: [/********:50538] <-> InitialHandler - encountered exception
java.lang.NullPointerException: null
	at net.md_5.bungee.util.CaseInsensitiveHashingStrategy.equals(CaseInsensitiveHashingStrategy.java:20) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
	at gnu.trove.map.hash.TCustomHashMap.get(TCustomHashMap.java:421) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
	at net.md_5.bungee.conf.Configuration.getServerInfo(Configuration.java:196) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
	at net.md_5.bungee.BungeeCord.getServerInfo(BungeeCord.java:655) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
	at net.md_5.bungee.api.AbstractReconnectHandler.getForcedHost(AbstractReconnectHandler.java:42) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
	at net.md_5.bungee.connection.InitialHandler.handle(InitialHandler.java:240) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
	at net.md_5.bungee.protocol.packet.StatusRequest.handle(StatusRequest.java:30) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:105) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
	at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:253) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:515) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9965730:unknown]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_291]
```
This may or may not be a completly different issue or  the origin off the issue above

**Comment by derklaro** [comment]
I'm closing this now as the Exceptions you see are caused by BungeeCord/Waterfall and not by CloudNet. However, i will take a look to use the suggested methods from issue #484.
