### ISSUE TITLE
When I enable the LabyMod config I get an error in Console and Module is not working

### ISSUE THREAD

**Issue by HOPSGESALZT** [CloudNetService/CloudNet-v3#610]
**Description of the bug:**

When I enable the LabyMod Module I get errors in the Console. 

**Steps to reproduce this bug:**

Steps to reproduce:
1. Go to 'LabyMod Module'
2. Enable the Module
3. See error in console of proxy

**Expected behavior:**

To function right

**Screenshots:**

```
[04.02 18:36:06.224] INFO: [PROXY-1] [18:36:05 ERROR]: de.dytanic.cloudnet.driver.event.EventListenerException: Error while invoking event listener handle in class eu.cloudnetservice.cloudnet.ext.labymod.listener.LabyModListener
[04.02 18:36:06.224] INFO: [PROXY-1] [18:36:05 ERROR]: 	at de.dytanic.cloudnet.driver.event.DefaultRegisteredEventListener.fireEvent(DefaultRegisteredEventListener.java:71)
[04.02 18:36:06.224] INFO: [PROXY-1] [18:36:05 ERROR]: 	at de.dytanic.cloudnet.driver.event.DefaultEventManager.fireEvent(DefaultEventManager.java:141)
[04.02 18:36:06.224] INFO: [PROXY-1] [18:36:05 ERROR]: 	at de.dytanic.cloudnet.driver.event.DefaultEventManager.fireEvent(DefaultEventManager.java:131)
[04.02 18:36:06.224] INFO: [PROXY-1] [18:36:05 ERROR]: 	at de.dytanic.cloudnet.driver.event.DefaultEventManager.callEvent(DefaultEventManager.java:118)
[04.02 18:36:06.224] INFO: [PROXY-1] [18:36:05 ERROR]: 	at de.dytanic.cloudnet.driver.event.IEventManager.callEvent(IEventManager.java:40)
[04.02 18:36:06.224] INFO: [PROXY-1] [18:36:05 ERROR]: 	at de.dytanic.cloudnet.wrapper.network.listener.PacketServerServiceInfoPublisherListener.invoke0(PacketServerServiceInfoPublisherListener.java:70)
[04.02 18:36:06.224] INFO: [PROXY-1] [18:36:05 ERROR]: 	at de.dytanic.cloudnet.wrapper.network.listener.PacketServerServiceInfoPublisherListener.handle(PacketServerServiceInfoPublisherListener.java:44)
[04.02 18:36:06.224] INFO: [PROXY-1] [18:36:05 ERROR]: 	at de.dytanic.cloudnet.driver.network.protocol.DefaultPacketListenerRegistry.handlePacket(DefaultPacketListenerRegistry.java:152)
[04.02 18:36:06.224] INFO: [PROXY-1] [18:36:05 ERROR]: 	at de.dytanic.cloudnet.driver.network.protocol.DefaultPacketListenerRegistry.handlePacket(DefaultPacketListenerRegistry.java:146)
[04.02 18:36:06.224] INFO: [PROXY-1] [18:36:05 ERROR]: 	at de.dytanic.cloudnet.driver.network.netty.NettyNetworkHandler.lambda$channelRead0$0(NettyNetworkHandler.java:67)
[04.02 18:36:06.224] INFO: [PROXY-1] [18:36:05 ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[04.02 18:36:06.224] INFO: [PROXY-1] [18:36:05 ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[04.02 18:36:06.224] INFO: [PROXY-1] [18:36:05 ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[04.02 18:36:06.224] INFO: [PROXY-1] [18:36:05 ERROR]: Caused by: java.lang.NullPointerException: Cannot invoke "eu.cloudnetservice.cloudnet.ext.labymod.config.LabyModConfiguration.isDiscordSpectateEnabled()" because the return value of "eu.cloudnetservice.cloudnet.ext.labymod.LabyModUtils.getConfiguration()" is null
[04.02 18:36:06.224] INFO: [PROXY-1] [18:36:05 ERROR]: 	at eu.cloudnetservice.cloudnet.ext.labymod.LabyModUtils.canSpectate(LabyModUtils.java:118)
[04.02 18:36:06.224] INFO: [PROXY-1] [18:36:05 ERROR]: 	at eu.cloudnetservice.cloudnet.ext.labymod.listener.LabyModListener.handle(LabyModListener.java:48)
[04.02 18:36:06.224] INFO: [PROXY-1] [18:36:05 ERROR]: 	at GeneratedListenerInvoker_34a7e660762547eb896492137ff4ba6f.invoke(GeneratedListenerInvoker_34a7e660762547eb896492137ff4ba6f.java)
[04.02 18:36:06.224] INFO: [PROXY-1] [18:36:05 ERROR]: 	at de.dytanic.cloudnet.driver.event.DefaultRegisteredEventListener.fireEvent(DefaultRegisteredEventListener.java:69)
[04.02 18:36:06.224] INFO: [PROXY-1] [18:36:05 ERROR]: 	... 12 more
```

**Environment and used hardware:**

 System specifications: 
 OS: Ubuntu20.04
 Version:  latest from 5 days ago

**Additional context (optional):**

**Comment by derklaro** [comment]
The actual configuration would be helpful, i guess you made a syntax error while editing the file...

**Comment by derklaro** [comment]
Closing due to inactivity.
