### ISSUE TITLE
CloudNet Nukkit Server kann sich nicht verbinden

### ISSUE THREAD

**Issue by ghost** [CloudNetService/CloudNet-v3#660]
Hey,

Ich habe ein Problem mit Nukkit und CloudNet:

Ich kann mich nicht auf den Server verbinden obwohl ich alles eingestellt habe (die Port-freigabe auf UDP gesetzt).
In der Konsole kommt auch kein Fehler oder Sonstiges alles startet normal.

Kann mir jemand sagen was ich falsch gemacht habe?

**Comment by kubo6472** [comment]
🇨🇦: Title: CloudNet Nukkit Server cannot connect
Contents: Hey,

I have a problem with Nukkit and CloudNet:

I can't connect to the server even though I've set everything (set the port forward to UDP).
There is no error or anything else in the console, everything starts normally.

Can someone tell me what I did wrong?

-----------------------------------------
Please use English so that more people can understand. Thanks. @Quinilo 
If you don't use the template, nobody would be able to help. You omitted what IP address did you use, to connect to the server. It might be something trivial like that. Please respond with a filled template or open a new issue and elaborate further, attaching screenshots if they help.

-----------------------------------------

**Comment by Quinilo** [comment]
There is an error with the Proxy (I use WaterdogPE)
`[28.07 21:55:25.784] WARNING: [Proxy-1] java.lang.reflect.InvocationTargetException
[28.07 21:55:25.784] WARNING: [Proxy-1]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[28.07 21:55:25.784] WARNING: [Proxy-1]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[28.07 21:55:25.784] WARNING: [Proxy-1]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[28.07 21:55:25.784] WARNING: [Proxy-1]         at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[28.07 21:55:25.784] WARNING: [Proxy-1]         at de.dytanic.cloudnet.wrapper.Wrapper.lambda$startApplication$5(Wrapper.java:487)
[28.07 21:55:25.784] WARNING: [Proxy-1]         at java.base/java.lang.Thread.run(Unknown Source)
[28.07 21:55:25.784] WARNING: [Proxy-1] Caused by: java.lang.IllegalAccessError: tried to access method dev.waterdog.waterdogpe.command.CommandSettings.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;)V from class dev.waterdog.waterdogpe.command.CommandSettings$Builder
[28.07 21:55:25.784] WARNING: [Proxy-1]         at dev.waterdog.waterdogpe.command.CommandSettings$Builder.build(CommandSettings.java:81)
[28.07 21:55:25.784] WARNING: [Proxy-1]         at dev.waterdog.waterdogpe.command.CommandSettings.<clinit>(CommandSettings.java:25)
[28.07 21:55:25.784] WARNING: [Proxy-1]         at dev.waterdog.waterdogpe.command.defaults.HelpCommand.<init>(HelpCommand.java:30)
[28.07 21:55:25.784] WARNING: [Proxy-1]         at dev.waterdog.waterdogpe.command.DefaultCommandMap.registerDefaults(DefaultCommandMap.java:29)
[28.07 21:55:25.784] WARNING: [Proxy-1]         at dev.waterdog.waterdogpe.command.DefaultCommandMap.<init>(DefaultCommandMap.java:25)
[28.07 21:55:25.784] WARNING: [Proxy-1]         at dev.waterdog.waterdogpe.ProxyServer.<init>(ProxyServer.java:164)
[28.07 21:55:25.784] WARNING: [Proxy-1]         at dev.waterdog.waterdogpe.WaterdogPE.main(WaterdogPE.java:56)
[28.07 21:55:25.784] WARNING: [Proxy-1]         ... 6 more`

**Comment by ghost** [comment]
> 🇨🇦: Title: CloudNet Nukkit Server cannot connect Contents: Hey,
> 
> I have a problem with Nukkit and CloudNet:
> 
> I can't connect to the server even though I've set everything (set the port forward to UDP). There is no error or anything else in the console, everything starts normally.
> 
> Can someone tell me what I did wrong?
> 
> Please use English so that more people can understand. Thanks. @Quinilo If you don't use the template, nobody would be able to help. You omitted what IP address did you use, to connect to the server. It might be something trivial like that. Please respond with a filled template or open a new issue and elaborate further, attaching screenshots if they help.

There is an error with the Proxy (I use WaterdogPE)
`[28.07 21:55:25.784] WARNING: [Proxy-1] java.lang.reflect.InvocationTargetException [28.07 21:55:25.784] WARNING: [Proxy-1] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [28.07 21:55:25.784] WARNING: [Proxy-1] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) [28.07 21:55:25.784] WARNING: [Proxy-1] at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) [28.07 21:55:25.784] WARNING: [Proxy-1] at java.base/java.lang.reflect.Method.invoke(Unknown Source) [28.07 21:55:25.784] WARNING: [Proxy-1] at de.dytanic.cloudnet.wrapper.Wrapper.lambda$startApplication$5(Wrapper.java:487) [28.07 21:55:25.784] WARNING: [Proxy-1] at java.base/java.lang.Thread.run(Unknown Source) [28.07 21:55:25.784] WARNING: [Proxy-1] Caused by: java.lang.IllegalAccessError: tried to access method dev.waterdog.waterdogpe.command.CommandSettings.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;)V from class dev.waterdog.waterdogpe.command.CommandSettings$Builder [28.07 21:55:25.784] WARNING: [Proxy-1] at dev.waterdog.waterdogpe.command.CommandSettings$Builder.build(CommandSettings.java:81) [28.07 21:55:25.784] WARNING: [Proxy-1] at dev.waterdog.waterdogpe.command.CommandSettings.<clinit>(CommandSettings.java:25) [28.07 21:55:25.784] WARNING: [Proxy-1] at dev.waterdog.waterdogpe.command.defaults.HelpCommand.<init>(HelpCommand.java:30) [28.07 21:55:25.784] WARNING: [Proxy-1] at dev.waterdog.waterdogpe.command.DefaultCommandMap.registerDefaults(DefaultCommandMap.java:29) [28.07 21:55:25.784] WARNING: [Proxy-1] at dev.waterdog.waterdogpe.command.DefaultCommandMap.<init>(DefaultCommandMap.java:25) [28.07 21:55:25.784] WARNING: [Proxy-1] at dev.waterdog.waterdogpe.ProxyServer.<init>(ProxyServer.java:164) [28.07 21:55:25.784] WARNING: [Proxy-1] at dev.waterdog.waterdogpe.WaterdogPE.main(WaterdogPE.java:56) [28.07 21:55:25.784] WARNING: [Proxy-1] ... 6 more`

**Comment by derklaro** [comment]
Semms to be a Waterdog issue and not related to CloudNet.
