### ISSUE TITLE
ServiceInfoSnapshotUtil.getPlayers ist immer Null

### ISSUE THREAD

**Issue by zandercodes** [CloudNetService/CloudNet-v3#78]
Hey Ihr Lieben,

ich weiß nicht ob das ein Bug ist oder ich etwas falsch mache aber wenn ich ServiceInfoSnapshotUtil.getPlayers(serviceInfoSnapshot) bekomme ich immer null zurück.

P.S. Das ist nur bei getPlayers null

Im code habe ich das stehen:

```
        for (ServiceInfoSnapshot serviceInfoSnapshot : CloudNetDriver.getInstance().getCloudService("Lobby")) {
            int players = ServiceInfoSnapshotUtil.getPlayers(serviceInfoSnapshot).size();
```

und players ist immer null.

und dieser Error kommt:
```
[30.07 21:23:33.763] INFO: [Lobby-1] org.bukkit.event.EventException: null
[30.07 21:23:33.763] INFO: [Lobby-1]    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
[30.07 21:23:33.763] INFO: [Lobby-1]    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
[30.07 21:23:33.763] INFO: [Lobby-1]    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-dcd1643-e60fc34]
[30.07 21:23:33.763] INFO: [Lobby-1]    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-dcd1643-e60fc34]
[30.07 21:23:33.763] INFO: [Lobby-1]    at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235) [spigot.jar:git-Spigot-dcd1643-e60fc34]
[30.07 21:23:33.763] INFO: [Lobby-1]    at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:202) [spigot.jar:git-Spigot-dcd1643-e60fc34]
[30.07 21:23:33.763] INFO: [Lobby-1]    at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:198) [spigot.jar:git-Spigot-dcd1643-e60fc34]
[30.07 21:23:33.763] INFO: [Lobby-1]    at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:991) [spigot.jar:git-Spigot-dcd1643-e60fc34]
[30.07 21:23:33.763] INFO: [Lobby-1]    at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26) [spigot.jar:git-Spigot-dcd1643-e60fc34]
[30.07 21:23:33.763] INFO: [Lobby-1]    at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot.jar:git-Spigot-dcd1643-e60fc34]
[30.07 21:23:33.763] INFO: [Lobby-1]    at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-dcd1643-e60fc34]
[30.07 21:23:33.763] INFO: [Lobby-1]    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_222]
[30.07 21:23:33.763] INFO: [Lobby-1]    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_222]
[30.07 21:23:33.763] INFO: [Lobby-1]    at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-dcd1643-e60fc34]
[30.07 21:23:33.763] INFO: [Lobby-1]    at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-dcd1643-e60fc34]
[30.07 21:23:33.763] INFO: [Lobby-1]    at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-dcd1643-e60fc34]
[30.07 21:23:33.763] INFO: [Lobby-1]    at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-dcd1643-e60fc34]
[30.07 21:23:33.763] INFO: [Lobby-1]    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-dcd1643-e60fc34]
[30.07 21:23:33.763] INFO: [Lobby-1]    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
[30.07 21:23:33.763] INFO: [Lobby-1] Caused by: java.lang.NullPointerException
[30.07 21:23:33.764] INFO: [Lobby-1]    at de.wildcards.lobbysystem.listeners.SwitcherMenu.invMenu(SwitcherMenu.java:53) ~[?:?]
[30.07 21:23:33.764] INFO: [Lobby-1]    at de.wildcards.lobbysystem.listeners.SwitcherMenu.onPlayerInteract(SwitcherMenu.java:32) ~[?:?]
[30.07 21:23:33.764] INFO: [Lobby-1]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
[30.07 21:23:33.764] INFO: [Lobby-1]    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
[30.07 21:23:33.764] INFO: [Lobby-1]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
[30.07 21:23:33.855] INFO: [Lobby-1]    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
[30.07 21:23:33.855] INFO: [Lobby-1]    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
[30.07 21:23:33.856] INFO: [Lobby-1]    ... 18 more
```

Minecraft version: Spigot 1.12.2
OS: Linux Debian

**Comment by realPanamo** [comment]
Hey,
Bist du dir sicher, dass der Fehler exakt aus der Zeile mit dem ``ServiceInfoSnapshotUtil.getPlayers`` kommt? Es könnte sehr gut sein, dass ``CloudNetDriver#getCloudService`` Null zurück gibt.
Du könntest aber auch mal die Methode ``ServiceInfoSnapshot.getOnlineCount`` probieren, die gibt dir direkt die Spieleranzahl.

**Comment by zandercodes** [comment]
Ja wenn ich ServiceInfoSnapshotUtil.getOnlineCount geht alles wunderbar.
Aber ich Versuche die Spielername von allen servern in einer Liste zuspeichern.
Aber das JsonDocument ist null.
Keine Ahnung woran das liegt.

**Comment by realPanamo** [comment]
Kann ich mir mal genauer ansehen

**Comment by McRuben** [comment]
Hey, lass dir doch einfach mal mit "paste SERVER" genau anzeigen, was in den Properties des ServiceInfoSnapshot bei "Players" steht

**Comment by zandercodes** [comment]
Alles klar versuche ich mal

**Comment by zandercodes** [comment]
Hier ist der log [https://hasteb.in/yezumuda](https://hasteb.in/yezumuda)

**Comment by McRuben** [comment]
Ah, ja, ih glaube, ich seh schon das Problem, ist dann wohl ein Bug, du kannst ja solange das noch nicht behoben ist "serviceInfo.getProperties().get("Players, TypeToken.getParameterized(Collection.class, JsonDocument.class))" verwenden, das müsstd funktionieren

**Comment by zandercodes** [comment]
Gefällt mir nicht das im log die Server ip steht.
```
[12:53:27 ERROR]: Could not pass event PlayerInteractEvent to Lobbysystem vv1.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:202) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:198) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:991) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_222]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_222]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.NullPointerException
	at de.wildcards.lobbysystem.listeners.SwitcherMenu.invMenu(SwitcherMenu.java:63) ~[?:?]
	at de.wildcards.lobbysystem.listeners.SwitcherMenu.onPlayerInteract(SwitcherMenu.java:37) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
	... 18 more

ServiceInfoSnapshot

{
  "creationTime": 1564570444403,
  "serviceId": {
    "uniqueId": "7c7fbb32-4e68-49ea-ad13-a1c887383446",
    "nodeUniqueId": "NodeZC-9948a119",
    "taskName": "Lobby",
    "taskServiceId": 1,
    "environment": "MINECRAFT_SERVER"
  },
  "address": {
    "host": "xx.xx.xx.xx",
    "port": xxxxx
  },
  "connected": true,
  "lifeCycle": "RUNNING",
  "processSnapshot": {
    "heapUsageMemory": 276103824,
    "noHeapUsageMemory": 74627152,
    "maxHeapMemory": 390070272,
    "currentLoadedClassCount": 8348,
    "totalLoadedClassCount": 8401,
    "unloadedClassCount": 53,
    "threads": [
      {
        "id": 31,
        "name": "Spigot Watchdog Thread",
        "threadState": "TIMED_WAITING",
        "daemon": false,
        "priority": 5
      },
      {
        "id": 28,
        "name": "Java2D Disposer",
        "threadState": "WAITING",
        "daemon": true,
        "priority": 10
      },
      {
        "id": 47,
        "name": "Netty Epoll Server IO #5",
        "threadState": "RUNNABLE",
        "daemon": true,
        "priority": 5
      },
      {
        "id": 38,
        "name": "DefaultTaskScheduler-1#2",
        "threadState": "TIMED_WAITING",
        "daemon": true,
        "priority": 1
      },
      {
        "id": 16,
        "name": "DefaultTaskScheduler-2#2",
        "threadState": "TIMED_WAITING",
        "daemon": true,
        "priority": 1
      },
      {
        "id": 25,
        "name": "Server Infinisleeper",
        "threadState": "TIMED_WAITING",
        "daemon": true,
        "priority": 5
      },
      {
        "id": 30,
        "name": "ObjectCleanerThread",
        "threadState": "TIMED_WAITING",
        "daemon": true,
        "priority": 1
      },
      {
        "id": 2,
        "name": "Reference Handler",
        "threadState": "WAITING",
        "daemon": true,
        "priority": 10
      },
      {
        "id": 41,
        "name": "Chunk I/O Executor Thread-1",
        "threadState": "WAITING",
        "daemon": true,
        "priority": 5
      },
      {
        "id": 37,
        "name": "File IO Thread",
        "threadState": "TIMED_WAITING",
        "daemon": false,
        "priority": 1
      },
      {
        "id": 1,
        "name": "main",
        "threadState": "RUNNABLE",
        "daemon": false,
        "priority": 5
      },
      {
        "id": 43,
        "name": "Netty Epoll Server IO #3",
        "threadState": "RUNNABLE",
        "daemon": true,
        "priority": 5
      },
      {
        "id": 15,
        "name": "DefaultTaskScheduler-2#1",
        "threadState": "TIMED_WAITING",
        "daemon": true,
        "priority": 1
      },
      {
        "id": 5,
        "name": "Signal Dispatcher",
        "threadState": "RUNNABLE",
        "daemon": true,
        "priority": 9
      },
      {
        "id": 21,
        "name": "Snooper Timer",
        "threadState": "TIMED_WAITING",
        "daemon": true,
        "priority": 5
      },
      {
        "id": 32,
        "name": "Spigot Metrics Thread",
        "threadState": "TIMED_WAITING",
        "daemon": true,
        "priority": 5
      },
      {
        "id": 34,
        "name": "DefaultTaskScheduler-1#1",
        "threadState": "TIMED_WAITING",
        "daemon": true,
        "priority": 1
      },
      {
        "id": 24,
        "name": "Server thread",
        "threadState": "TIMED_WAITING",
        "daemon": false,
        "priority": 5
      },
      {
        "id": 3,
        "name": "Finalizer",
        "threadState": "WAITING",
        "daemon": true,
        "priority": 8
      },
      {
        "id": 45,
        "name": "Netty Epoll Server IO #4",
        "threadState": "RUNNABLE",
        "daemon": true,
        "priority": 5
      },
      {
        "id": 27,
        "name": "Thread-7",
        "threadState": "WAITING",
        "daemon": false,
        "priority": 5
      },
      {
        "id": 39,
        "name": "Netty Epoll Server IO #2",
        "threadState": "RUNNABLE",
        "daemon": true,
        "priority": 5
      },
      {
        "id": 35,
        "name": "Netty Epoll Server IO #1",
        "threadState": "RUNNABLE",
        "daemon": true,
        "priority": 5
      },
      {
        "id": 33,
        "name": "Netty Epoll Server IO #0",
        "threadState": "RUNNABLE",
        "daemon": true,
        "priority": 5
      },
      {
        "id": 26,
        "name": "Server console handler",
        "threadState": "RUNNABLE",
        "daemon": true,
        "priority": 5
      },
      {
        "id": 11,
        "name": "Thread-0",
        "threadState": "WAITING",
        "daemon": false,
        "priority": 1
      },
      {
        "id": 14,
        "name": "multithreadEventExecutorGroup-1-1",
        "threadState": "RUNNABLE",
        "daemon": true,
        "priority": 1
      }
    ],
    "cpuUsage": 0.4706465196928412
  },
  "configuration": {
    "serviceId": {
      "uniqueId": "7c7fbb32-4e68-49ea-ad13-a1c887383446",
      "nodeUniqueId": "NodeZC-9948a119",
      "taskName": "Lobby",
      "taskServiceId": 1,
      "environment": "MINECRAFT_SERVER"
    },
    "runtime": "jvm",
    "autoDeleteOnStop": true,
    "staticService": false,
    "groups": [
      "Lobby"
    ],
    "includes": [],
    "templates": [
      {
        "prefix": "Lobby",
        "name": "default",
        "storage": "local"
      }
    ],
    "deployments": [],
    "processConfig": {
      "environment": "MINECRAFT_SERVER",
      "maxHeapMemorySize": 372,
      "jvmOptions": []
    },
    "port": xxxxx,
    "properties": {}
  },
  "properties": {
    "Online": true,
    "Version": "git-Spigot-dcd1643-e60fc34 (MC: 1.12.2)",
    "Bukkit-Version": "1.12.2-R0.1-SNAPSHOT",
    "Online-Count": 1,
    "Max-Players": 25,
    "Motd": "WildCards service",
    "Extra": "",
    "State": "LOBBY",
    "Outgoing-Channels": [
      "cloudnet:main",
      "BungeeCord"
    ],
    "Incoming-Channels": [],
    "Online-Mode": false,
    "Whitelist-Enabled": false,
    "Whitelist": [],
    "Allow-Nether": false,
    "Allow-End": false,
    "Players": [
      {
        "uniqueId": "7337b352-9371-488d-9332-dba1cb2d6e95",
        "name": "CrafterGamer",
        "health": 20.0,
        "maxHealth": 20.0,
        "saturation": 20.0,
        "level": 0,
        "location": {
          "x": 242.5,
          "y": 63.0,
          "z": 1348.5,
          "yaw": -19.049997329711914,
          "pitch": -5.40000057220459,
          "world": "Hub"
        },
        "address": {
          "host": "xx.xx.xx.xx",
          "port": xxxxx
        }
      }
    ],
    "Plugins": [
      {
        "name": "CloudNet-Bridge",
        "version": "1.0",
        "properties": {
          "authors": [
            "Dytanic"
          ],
          "dependencies": [],
          "load-before": [],
          "description": "Bukkit extension for the CloudNet runtime, which optimize some features",
          "soft-dependencies": [],
          "main-class": "de.dytanic.cloudnet.ext.bridge.bukkit.BukkitCloudNetBridgePlugin"
        }
      },
      {
        "name": "CloudNet-CloudPerms",
        "version": "1.0",
        "properties": {
          "authors": [
            "Dytanic"
          ],
          "dependencies": [],
          "load-before": [],
          "description": "Bukkit extension which implement the permission management system from CloudNet into Bukkit for players",
          "soft-dependencies": [],
          "main-class": "de.dytanic.cloudnet.ext.cloudperms.bukkit.BukkitCloudNetCloudPermissionsPlugin"
        }
      },
      {
        "name": "Lobbysystem",
        "version": "v1.0",
        "properties": {
          "authors": [
            "CrafterGamer"
          ],
          "dependencies": [
            "CloudNet-Bridge",
            "CloudNet-CloudPerms"
          ],
          "load-before": [],
          "commands": {
            "build": {
              "description": "Build",
              "usage": "/build"
            }
          },
          "soft-dependencies": [],
          "main-class": "de.wildcards.lobbysystem.Main"
        }
      },
      {
        "name": "CloudNet-Signs",
        "version": "1.0",
        "properties": {
          "authors": [
            "Dytanic"
          ],
          "dependencies": [
            "CloudNet-Bridge"
          ],
          "load-before": [],
          "description": "Bukkit extension for the CloudNet runtime, which optimize some features",
          "commands": {
            "cloudsign": {
              "aliases": [
                "cs"
              ]
            }
          },
          "soft-dependencies": [],
          "website": "https://cloudnetservice.eu",
          "main-class": "de.dytanic.cloudnet.ext.signs.bukkit.BukkitCloudNetSignsPlugin"
        }
      }
    ],
    "Worlds": [
      {
        "uniqueId": "2f992acc-ddc9-46cf-8ff9-182e3e5756c8",
        "name": "Hub",
        "difficulty": "PEACEFUL",
        "gameRules": {
          "doTileDrops": "true",
          "doFireTick": "true",
          "gameLoopFunction": "-",
          "maxCommandChainLength": "65536",
          "reducedDebugInfo": "false",
          "naturalRegeneration": "true",
          "disableElytraMovementCheck": "false",
          "doMobLoot": "true",
          "announceAdvancements": "false",
          "keepInventory": "false",
          "doEntityDrops": "true",
          "doLimitedCrafting": "false",
          "mobGriefing": "true",
          "randomTickSpeed": "3",
          "commandBlockOutput": "true",
          "spawnRadius": "10",
          "doMobSpawning": "false",
          "maxEntityCramming": "24",
          "logAdminCommands": "true",
          "spectatorsGenerateChunks": "true",
          "doWeatherCycle": "false",
          "sendCommandFeedback": "true",
          "doDaylightCycle": "false",
          "showDeathMessages": "true"
        }
      }
    ]
  }
}
```

**Comment by zandercodes** [comment]
> Ah, ja, ih glaube, ich seh schon das Problem, ist dann wohl ein Bug, du kannst ja solange das noch nicht behoben ist "serviceInfo.getProperties().get("Players, TypeToken.getParameterized(Collection.class, JsonDocument.class))" verwenden, das müsstd funktionieren

Oke werde ich mal versuchen und Danke

**Comment by zandercodes** [comment]
> > Ah, ja, ih glaube, ich seh schon das Problem, ist dann wohl ein Bug, du kannst ja solange das noch nicht behoben ist "serviceInfo.getProperties().get("Players, TypeToken.getParameterized(Collection.class, JsonDocument.class))" verwenden, das müsstd funktionieren
> 
> Oke werde ich mal versuchen und Danke

Das funktioniert Wunderbar aber ist nicht die Optimalste lösung.
Danke @McRuben
